// bsp_top_altera_mm_interconnect_1920_jcriroa.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module bsp_top_altera_mm_interconnect_1920_jcriroa (
		input  wire [7:0]  bar2_pr_cc_bridge_m0_address,                                          //                                            bar2_pr_cc_bridge_m0.address
		output wire        bar2_pr_cc_bridge_m0_waitrequest,                                      //                                                                .waitrequest
		input  wire [0:0]  bar2_pr_cc_bridge_m0_burstcount,                                       //                                                                .burstcount
		input  wire [3:0]  bar2_pr_cc_bridge_m0_byteenable,                                       //                                                                .byteenable
		input  wire        bar2_pr_cc_bridge_m0_read,                                             //                                                                .read
		output wire [31:0] bar2_pr_cc_bridge_m0_readdata,                                         //                                                                .readdata
		output wire        bar2_pr_cc_bridge_m0_readdatavalid,                                    //                                                                .readdatavalid
		input  wire        bar2_pr_cc_bridge_m0_write,                                            //                                                                .write
		input  wire [31:0] bar2_pr_cc_bridge_m0_writedata,                                        //                                                                .writedata
		input  wire        bar2_pr_cc_bridge_m0_debugaccess,                                      //                                                                .debugaccess
		output wire [3:0]  pr_controller_avmm_slave_address,                                      //                                        pr_controller_avmm_slave.address
		output wire        pr_controller_avmm_slave_write,                                        //                                                                .write
		output wire        pr_controller_avmm_slave_read,                                         //                                                                .read
		input  wire [31:0] pr_controller_avmm_slave_readdata,                                     //                                                                .readdata
		output wire [31:0] pr_controller_avmm_slave_writedata,                                    //                                                                .writedata
		input  wire        pr_controller_avmm_slave_waitrequest,                                  //                                                                .waitrequest
		input  wire        bar2_pr_cc_bridge_m0_translator_reset_reset_bridge_in_reset_reset,     //     bar2_pr_cc_bridge_m0_translator_reset_reset_bridge_in_reset.reset
		input  wire        pr_controller_avmm_slave_translator_reset_reset_bridge_in_reset_reset, // pr_controller_avmm_slave_translator_reset_reset_bridge_in_reset.reset
		input  wire        iopll_0_outclk0_clk                                                    //                                                 iopll_0_outclk0.clk
	);

	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_waitrequest;   // pr_controller_avmm_slave_translator:uav_waitrequest -> bar2_pr_cc_bridge_m0_translator:uav_waitrequest
	wire  [31:0] bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdata;      // pr_controller_avmm_slave_translator:uav_readdata -> bar2_pr_cc_bridge_m0_translator:uav_readdata
	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_debugaccess;   // bar2_pr_cc_bridge_m0_translator:uav_debugaccess -> pr_controller_avmm_slave_translator:uav_debugaccess
	wire   [7:0] bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_address;       // bar2_pr_cc_bridge_m0_translator:uav_address -> pr_controller_avmm_slave_translator:uav_address
	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_read;          // bar2_pr_cc_bridge_m0_translator:uav_read -> pr_controller_avmm_slave_translator:uav_read
	wire   [3:0] bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_byteenable;    // bar2_pr_cc_bridge_m0_translator:uav_byteenable -> pr_controller_avmm_slave_translator:uav_byteenable
	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdatavalid; // pr_controller_avmm_slave_translator:uav_readdatavalid -> bar2_pr_cc_bridge_m0_translator:uav_readdatavalid
	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_lock;          // bar2_pr_cc_bridge_m0_translator:uav_lock -> pr_controller_avmm_slave_translator:uav_lock
	wire         bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_write;         // bar2_pr_cc_bridge_m0_translator:uav_write -> pr_controller_avmm_slave_translator:uav_write
	wire  [31:0] bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_writedata;     // bar2_pr_cc_bridge_m0_translator:uav_writedata -> pr_controller_avmm_slave_translator:uav_writedata
	wire   [2:0] bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_burstcount;    // bar2_pr_cc_bridge_m0_translator:uav_burstcount -> pr_controller_avmm_slave_translator:uav_burstcount

	bsp_top_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (8),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (8),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) bar2_pr_cc_bridge_m0_translator (
		.clk                    (iopll_0_outclk0_clk),                                                     //   input,   width = 1,                       clk.clk
		.reset                  (bar2_pr_cc_bridge_m0_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                     reset.reset
		.uav_address            (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_address),       //  output,   width = 8, avalon_universal_master_0.address
		.uav_burstcount         (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (bar2_pr_cc_bridge_m0_address),                                            //   input,   width = 8,      avalon_anti_master_0.address
		.av_waitrequest         (bar2_pr_cc_bridge_m0_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_burstcount          (bar2_pr_cc_bridge_m0_burstcount),                                         //   input,   width = 1,                          .burstcount
		.av_byteenable          (bar2_pr_cc_bridge_m0_byteenable),                                         //   input,   width = 4,                          .byteenable
		.av_read                (bar2_pr_cc_bridge_m0_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (bar2_pr_cc_bridge_m0_readdata),                                           //  output,  width = 32,                          .readdata
		.av_readdatavalid       (bar2_pr_cc_bridge_m0_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (bar2_pr_cc_bridge_m0_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (bar2_pr_cc_bridge_m0_writedata),                                          //   input,  width = 32,                          .writedata
		.av_debugaccess         (bar2_pr_cc_bridge_m0_debugaccess),                                        //   input,   width = 1,                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                    // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                    // (terminated),                                        
		.av_chipselect          (1'b0),                                                                    // (terminated),                                        
		.av_lock                (1'b0),                                                                    // (terminated),                                        
		.uav_clken              (),                                                                        // (terminated),                                        
		.av_clken               (1'b1),                                                                    // (terminated),                                        
		.uav_response           (2'b00),                                                                   // (terminated),                                        
		.av_response            (),                                                                        // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                    // (terminated),                                        
		.av_writeresponsevalid  ()                                                                         // (terminated),                                        
	);

	bsp_top_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (4),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (8),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) pr_controller_avmm_slave_translator (
		.clk                    (iopll_0_outclk0_clk),                                                     //   input,   width = 1,                      clk.clk
		.reset                  (pr_controller_avmm_slave_translator_reset_reset_bridge_in_reset_reset),   //   input,   width = 1,                    reset.reset
		.uav_address            (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_address),       //   input,   width = 8, avalon_universal_slave_0.address
		.uav_burstcount         (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (bar2_pr_cc_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (pr_controller_avmm_slave_address),                                        //  output,   width = 4,      avalon_anti_slave_0.address
		.av_write               (pr_controller_avmm_slave_write),                                          //  output,   width = 1,                         .write
		.av_read                (pr_controller_avmm_slave_read),                                           //  output,   width = 1,                         .read
		.av_readdata            (pr_controller_avmm_slave_readdata),                                       //   input,  width = 32,                         .readdata
		.av_writedata           (pr_controller_avmm_slave_writedata),                                      //  output,  width = 32,                         .writedata
		.av_waitrequest         (pr_controller_avmm_slave_waitrequest),                                    //   input,   width = 1,                         .waitrequest
		.av_begintransfer       (),                                                                        // (terminated),                                       
		.av_beginbursttransfer  (),                                                                        // (terminated),                                       
		.av_burstcount          (),                                                                        // (terminated),                                       
		.av_byteenable          (),                                                                        // (terminated),                                       
		.av_readdatavalid       (1'b0),                                                                    // (terminated),                                       
		.av_writebyteenable     (),                                                                        // (terminated),                                       
		.av_lock                (),                                                                        // (terminated),                                       
		.av_chipselect          (),                                                                        // (terminated),                                       
		.av_clken               (),                                                                        // (terminated),                                       
		.uav_clken              (1'b0),                                                                    // (terminated),                                       
		.av_debugaccess         (),                                                                        // (terminated),                                       
		.av_outputenable        (),                                                                        // (terminated),                                       
		.uav_response           (),                                                                        // (terminated),                                       
		.av_response            (2'b00),                                                                   // (terminated),                                       
		.uav_writeresponsevalid (),                                                                        // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                     // (terminated),                                       
	);

endmodule
