// local_qsys_sld_jtag_bridge_host_0.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module local_qsys_sld_jtag_bridge_host_0 (
		input  wire  tck,     // connect_to_bridge_host.tck
		input  wire  tms,     //                       .tms
		input  wire  tdi,     //                       .tdi
		input  wire  vir_tdi, //                       .vir_tdi
		input  wire  ena,     //                       .ena
		output wire  tdo      //                       .tdo
	);

	altera_sld_jtag_bridge_host_wrapper #(
		.NAME (" ")
	) sld_jtag_bridge_host_0 (
		.tck     (tck),     //   input,  width = 1, connect_to_bridge_host.tck
		.tms     (tms),     //   input,  width = 1,                       .tms
		.tdi     (tdi),     //   input,  width = 1,                       .tdi
		.vir_tdi (vir_tdi), //   input,  width = 1,                       .vir_tdi
		.ena     (ena),     //   input,  width = 1,                       .ena
		.tdo     (tdo)      //  output,  width = 1,                       .tdo
	);

endmodule
