#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

if [[ $target_board == "arty" ]]; then
    target_part="xc7a35ticsg324-1L"
    part_vendor="Xilinx"
elif [[ $target_board == "arty-a7-100" ]]; then
    target_part="xc7a100tcsg324-1"
    part_vendor="Xilinx"
elif [[ $target_board == "vc709" ]]; then
    target_part="xc7vx690tffg1761-2"
    part_vendor="Xilinx"
elif [[ $target_board == "vcu118" ]]; then
    target_part="xcvu9p-flga2104-2L-e"
    part_vendor="Xilinx"
elif [[ $target_board == "arria10" ]]; then
    target_part="ARRIA10"
    part_vendor="Intel"
fi
