// local_qsys_reset_in.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module local_qsys_reset_in (
		input  wire  clk,         //       clk.clk
		input  wire  in_reset_n,  //  in_reset.reset_n
		output wire  out_reset_n  // out_reset.reset_n
	);

	assign out_reset_n = in_reset_n;

endmodule
