// local_qsys_pr_handshake_0.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module local_qsys_pr_handshake_0 (
		input  wire  clk,                    //        clock.clk
		input  wire  rst,                    //   reset_sink.reset
		input  wire  pr_handshake_start_req, // pr_handshake.start_req
		output wire  pr_handshake_start_ack, //             .start_ack
		input  wire  pr_handshake_stop_req,  //             .stop_req
		output wire  pr_handshake_stop_ack   //             .stop_ack
	);

	pr_handshake pr_handshake_0 (
		.clk                    (clk),                    //   input,  width = 1,        clock.clk
		.rst                    (rst),                    //   input,  width = 1,   reset_sink.reset
		.pr_handshake_start_req (pr_handshake_start_req), //   input,  width = 1, pr_handshake.start_req
		.pr_handshake_start_ack (pr_handshake_start_ack), //  output,  width = 1,             .start_ack
		.pr_handshake_stop_req  (pr_handshake_stop_req),  //   input,  width = 1,             .stop_req
		.pr_handshake_stop_ack  (pr_handshake_stop_ack)   //  output,  width = 1,             .stop_ack
	);

endmodule
