# TCL File Generated by Component Editor 20.2
# Fri Nov 27 11:31:21 CET 2020
# DO NOT MODIFY


# 
# pr_handshake "pr_handshake" v1.0
# RR 2020.11.27.11:31:21
# partial Reconfiguration Handshake Acknowledge
# 

# 
# request TCL package from ACDS 20.1
# 
package require -exact qsys 20.1


# 
# module pr_handshake
# 
set_module_property DESCRIPTION "partial Reconfiguration Handshake Acknowledge"
set_module_property NAME pr_handshake
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP PR
set_module_property AUTHOR RR
set_module_property DISPLAY_NAME pr_handshake
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pr_handshake
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_handshake.sv SYSTEM_VERILOG PATH pr_handshake.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point pr_handshake
# 
add_interface pr_handshake conduit end
set_interface_property pr_handshake associatedClock ""
set_interface_property pr_handshake associatedReset ""
set_interface_property pr_handshake ENABLED true
set_interface_property pr_handshake EXPORT_OF ""
set_interface_property pr_handshake PORT_NAME_MAP ""
set_interface_property pr_handshake CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake SVD_ADDRESS_GROUP ""
set_interface_property pr_handshake IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port pr_handshake pr_handshake_start_req start_req Input 1
add_interface_port pr_handshake pr_handshake_start_ack start_ack Output 1
add_interface_port pr_handshake pr_handshake_stop_req stop_req Input 1
add_interface_port pr_handshake pr_handshake_stop_ack stop_ack Output 1

