// ddr4_calibration_pio.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module ddr4_calibration_pio (
		input  wire        clk,      //                 clk.clk
		input  wire        reset_n,  //               reset.reset_n
		input  wire [1:0]  address,  //                  s1.address
		output wire [31:0] readdata, //                    .readdata
		input  wire [31:0] in_port   // external_connection.export
	);

	ddr4_calibration_pio_altera_avalon_pio_1912_os5mnhq pcie_subsystem_pio_0 (
		.clk      (clk),      //   input,   width = 1,                 clk.clk
		.reset_n  (reset_n),  //   input,   width = 1,               reset.reset_n
		.address  (address),  //   input,   width = 2,                  s1.address
		.readdata (readdata), //  output,  width = 32,                    .readdata
		.in_port  (in_port)   //   input,  width = 32, external_connection.export
	);

endmodule
