// local_qsys_intel_configuration_reset_release_to_debug_logic_0.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module local_qsys_intel_configuration_reset_release_to_debug_logic_0 (
		input  wire  conf_reset  // conf_reset_in.reset
	);

	intel_configuration_reset_release_to_debug_logic intel_configuration_reset_release_to_debug_logic_0 (
		.conf_reset (conf_reset)  //   input,  width = 1, conf_reset_in.reset
	);

endmodule
