// bsp_top_altera_mm_interconnect_1920_w5sb34q.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module bsp_top_altera_mm_interconnect_1920_w5sb34q (
		input  wire [30:0] bar4_emif_ase_expanded_master_address,                                      //                                        bar4_emif_ase_expanded_master.address
		output wire        bar4_emif_ase_expanded_master_waitrequest,                                  //                                                                     .waitrequest
		input  wire [3:0]  bar4_emif_ase_expanded_master_burstcount,                                   //                                                                     .burstcount
		input  wire [7:0]  bar4_emif_ase_expanded_master_byteenable,                                   //                                                                     .byteenable
		input  wire        bar4_emif_ase_expanded_master_read,                                         //                                                                     .read
		output wire [63:0] bar4_emif_ase_expanded_master_readdata,                                     //                                                                     .readdata
		output wire        bar4_emif_ase_expanded_master_readdatavalid,                                //                                                                     .readdatavalid
		input  wire        bar4_emif_ase_expanded_master_write,                                        //                                                                     .write
		input  wire [63:0] bar4_emif_ase_expanded_master_writedata,                                    //                                                                     .writedata
		output wire [30:0] bar4_emif_cc_bridge_s0_address,                                             //                                               bar4_emif_cc_bridge_s0.address
		output wire        bar4_emif_cc_bridge_s0_write,                                               //                                                                     .write
		output wire        bar4_emif_cc_bridge_s0_read,                                                //                                                                     .read
		input  wire [63:0] bar4_emif_cc_bridge_s0_readdata,                                            //                                                                     .readdata
		output wire [63:0] bar4_emif_cc_bridge_s0_writedata,                                           //                                                                     .writedata
		output wire [2:0]  bar4_emif_cc_bridge_s0_burstcount,                                          //                                                                     .burstcount
		output wire [7:0]  bar4_emif_cc_bridge_s0_byteenable,                                          //                                                                     .byteenable
		input  wire        bar4_emif_cc_bridge_s0_readdatavalid,                                       //                                                                     .readdatavalid
		input  wire        bar4_emif_cc_bridge_s0_waitrequest,                                         //                                                                     .waitrequest
		output wire        bar4_emif_cc_bridge_s0_debugaccess,                                         //                                                                     .debugaccess
		input  wire        bar4_emif_ase_reset_reset_bridge_in_reset_reset,                            //                            bar4_emif_ase_reset_reset_bridge_in_reset.reset
		input  wire        bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset, // bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset.reset
		input  wire        a10_pcie_coreclkout_hip_clk                                                 //                                              a10_pcie_coreclkout_hip.clk
	);

	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_waitrequest;   // bar4_emif_ase_expanded_master_agent:av_waitrequest -> bar4_emif_ase_expanded_master_translator:uav_waitrequest
	wire   [63:0] bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdata;      // bar4_emif_ase_expanded_master_agent:av_readdata -> bar4_emif_ase_expanded_master_translator:uav_readdata
	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_debugaccess;   // bar4_emif_ase_expanded_master_translator:uav_debugaccess -> bar4_emif_ase_expanded_master_agent:av_debugaccess
	wire   [30:0] bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_address;       // bar4_emif_ase_expanded_master_translator:uav_address -> bar4_emif_ase_expanded_master_agent:av_address
	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_read;          // bar4_emif_ase_expanded_master_translator:uav_read -> bar4_emif_ase_expanded_master_agent:av_read
	wire    [7:0] bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_byteenable;    // bar4_emif_ase_expanded_master_translator:uav_byteenable -> bar4_emif_ase_expanded_master_agent:av_byteenable
	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdatavalid; // bar4_emif_ase_expanded_master_agent:av_readdatavalid -> bar4_emif_ase_expanded_master_translator:uav_readdatavalid
	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_lock;          // bar4_emif_ase_expanded_master_translator:uav_lock -> bar4_emif_ase_expanded_master_agent:av_lock
	wire          bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_write;         // bar4_emif_ase_expanded_master_translator:uav_write -> bar4_emif_ase_expanded_master_agent:av_write
	wire   [63:0] bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_writedata;     // bar4_emif_ase_expanded_master_translator:uav_writedata -> bar4_emif_ase_expanded_master_agent:av_writedata
	wire    [6:0] bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_burstcount;    // bar4_emif_ase_expanded_master_translator:uav_burstcount -> bar4_emif_ase_expanded_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                                // rsp_mux:src_valid -> bar4_emif_ase_expanded_master_agent:rp_valid
	wire  [149:0] rsp_mux_src_data;                                                                 // rsp_mux:src_data -> bar4_emif_ase_expanded_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                                // bar4_emif_ase_expanded_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                              // rsp_mux:src_channel -> bar4_emif_ase_expanded_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                        // rsp_mux:src_startofpacket -> bar4_emif_ase_expanded_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                          // rsp_mux:src_endofpacket -> bar4_emif_ase_expanded_master_agent:rp_endofpacket
	wire   [63:0] bar4_emif_cc_bridge_s0_agent_m0_readdata;                                         // bar4_emif_cc_bridge_s0_translator:uav_readdata -> bar4_emif_cc_bridge_s0_agent:m0_readdata
	wire          bar4_emif_cc_bridge_s0_agent_m0_waitrequest;                                      // bar4_emif_cc_bridge_s0_translator:uav_waitrequest -> bar4_emif_cc_bridge_s0_agent:m0_waitrequest
	wire          bar4_emif_cc_bridge_s0_agent_m0_debugaccess;                                      // bar4_emif_cc_bridge_s0_agent:m0_debugaccess -> bar4_emif_cc_bridge_s0_translator:uav_debugaccess
	wire   [30:0] bar4_emif_cc_bridge_s0_agent_m0_address;                                          // bar4_emif_cc_bridge_s0_agent:m0_address -> bar4_emif_cc_bridge_s0_translator:uav_address
	wire    [7:0] bar4_emif_cc_bridge_s0_agent_m0_byteenable;                                       // bar4_emif_cc_bridge_s0_agent:m0_byteenable -> bar4_emif_cc_bridge_s0_translator:uav_byteenable
	wire          bar4_emif_cc_bridge_s0_agent_m0_read;                                             // bar4_emif_cc_bridge_s0_agent:m0_read -> bar4_emif_cc_bridge_s0_translator:uav_read
	wire          bar4_emif_cc_bridge_s0_agent_m0_readdatavalid;                                    // bar4_emif_cc_bridge_s0_translator:uav_readdatavalid -> bar4_emif_cc_bridge_s0_agent:m0_readdatavalid
	wire          bar4_emif_cc_bridge_s0_agent_m0_lock;                                             // bar4_emif_cc_bridge_s0_agent:m0_lock -> bar4_emif_cc_bridge_s0_translator:uav_lock
	wire   [63:0] bar4_emif_cc_bridge_s0_agent_m0_writedata;                                        // bar4_emif_cc_bridge_s0_agent:m0_writedata -> bar4_emif_cc_bridge_s0_translator:uav_writedata
	wire          bar4_emif_cc_bridge_s0_agent_m0_write;                                            // bar4_emif_cc_bridge_s0_agent:m0_write -> bar4_emif_cc_bridge_s0_translator:uav_write
	wire    [5:0] bar4_emif_cc_bridge_s0_agent_m0_burstcount;                                       // bar4_emif_cc_bridge_s0_agent:m0_burstcount -> bar4_emif_cc_bridge_s0_translator:uav_burstcount
	wire          bar4_emif_cc_bridge_s0_agent_rf_source_valid;                                     // bar4_emif_cc_bridge_s0_agent:rf_source_valid -> bar4_emif_cc_bridge_s0_agent_rsp_fifo:in_valid
	wire  [150:0] bar4_emif_cc_bridge_s0_agent_rf_source_data;                                      // bar4_emif_cc_bridge_s0_agent:rf_source_data -> bar4_emif_cc_bridge_s0_agent_rsp_fifo:in_data
	wire          bar4_emif_cc_bridge_s0_agent_rf_source_ready;                                     // bar4_emif_cc_bridge_s0_agent_rsp_fifo:in_ready -> bar4_emif_cc_bridge_s0_agent:rf_source_ready
	wire          bar4_emif_cc_bridge_s0_agent_rf_source_startofpacket;                             // bar4_emif_cc_bridge_s0_agent:rf_source_startofpacket -> bar4_emif_cc_bridge_s0_agent_rsp_fifo:in_startofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rf_source_endofpacket;                               // bar4_emif_cc_bridge_s0_agent:rf_source_endofpacket -> bar4_emif_cc_bridge_s0_agent_rsp_fifo:in_endofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_valid;                                  // bar4_emif_cc_bridge_s0_agent_rsp_fifo:out_valid -> bar4_emif_cc_bridge_s0_agent:rf_sink_valid
	wire  [150:0] bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_data;                                   // bar4_emif_cc_bridge_s0_agent_rsp_fifo:out_data -> bar4_emif_cc_bridge_s0_agent:rf_sink_data
	wire          bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_ready;                                  // bar4_emif_cc_bridge_s0_agent:rf_sink_ready -> bar4_emif_cc_bridge_s0_agent_rsp_fifo:out_ready
	wire          bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_startofpacket;                          // bar4_emif_cc_bridge_s0_agent_rsp_fifo:out_startofpacket -> bar4_emif_cc_bridge_s0_agent:rf_sink_startofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_endofpacket;                            // bar4_emif_cc_bridge_s0_agent_rsp_fifo:out_endofpacket -> bar4_emif_cc_bridge_s0_agent:rf_sink_endofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_valid;                                // bar4_emif_cc_bridge_s0_agent:rdata_fifo_src_valid -> bar4_emif_cc_bridge_s0_agent:rdata_fifo_sink_valid
	wire   [65:0] bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_data;                                 // bar4_emif_cc_bridge_s0_agent:rdata_fifo_src_data -> bar4_emif_cc_bridge_s0_agent:rdata_fifo_sink_data
	wire          bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_ready;                                // bar4_emif_cc_bridge_s0_agent:rdata_fifo_sink_ready -> bar4_emif_cc_bridge_s0_agent:rdata_fifo_src_ready
	wire          bar4_emif_ase_expanded_master_agent_cp_valid;                                     // bar4_emif_ase_expanded_master_agent:cp_valid -> router:sink_valid
	wire  [149:0] bar4_emif_ase_expanded_master_agent_cp_data;                                      // bar4_emif_ase_expanded_master_agent:cp_data -> router:sink_data
	wire          bar4_emif_ase_expanded_master_agent_cp_ready;                                     // router:sink_ready -> bar4_emif_ase_expanded_master_agent:cp_ready
	wire          bar4_emif_ase_expanded_master_agent_cp_startofpacket;                             // bar4_emif_ase_expanded_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          bar4_emif_ase_expanded_master_agent_cp_endofpacket;                               // bar4_emif_ase_expanded_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                                 // router:src_valid -> cmd_demux:sink_valid
	wire  [149:0] router_src_data;                                                                  // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                                 // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                               // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                         // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                           // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          router_001_src_valid;                                                             // router_001:src_valid -> rsp_demux:sink_valid
	wire  [149:0] router_001_src_data;                                                              // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                             // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                           // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                     // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                       // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                                                // cmd_mux:src_valid -> bar4_emif_cc_bridge_s0_burst_adapter:sink0_valid
	wire  [149:0] cmd_mux_src_data;                                                                 // cmd_mux:src_data -> bar4_emif_cc_bridge_s0_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                                                // bar4_emif_cc_bridge_s0_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                              // cmd_mux:src_channel -> bar4_emif_cc_bridge_s0_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                                        // cmd_mux:src_startofpacket -> bar4_emif_cc_bridge_s0_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                                          // cmd_mux:src_endofpacket -> bar4_emif_cc_bridge_s0_burst_adapter:sink0_endofpacket
	wire          bar4_emif_cc_bridge_s0_burst_adapter_source0_valid;                               // bar4_emif_cc_bridge_s0_burst_adapter:source0_valid -> agent_pipeline:in_valid
	wire  [149:0] bar4_emif_cc_bridge_s0_burst_adapter_source0_data;                                // bar4_emif_cc_bridge_s0_burst_adapter:source0_data -> agent_pipeline:in_data
	wire          bar4_emif_cc_bridge_s0_burst_adapter_source0_ready;                               // agent_pipeline:in_ready -> bar4_emif_cc_bridge_s0_burst_adapter:source0_ready
	wire    [0:0] bar4_emif_cc_bridge_s0_burst_adapter_source0_channel;                             // bar4_emif_cc_bridge_s0_burst_adapter:source0_channel -> agent_pipeline:in_channel
	wire          bar4_emif_cc_bridge_s0_burst_adapter_source0_startofpacket;                       // bar4_emif_cc_bridge_s0_burst_adapter:source0_startofpacket -> agent_pipeline:in_startofpacket
	wire          bar4_emif_cc_bridge_s0_burst_adapter_source0_endofpacket;                         // bar4_emif_cc_bridge_s0_burst_adapter:source0_endofpacket -> agent_pipeline:in_endofpacket
	wire          agent_pipeline_source0_valid;                                                     // agent_pipeline:out_valid -> bar4_emif_cc_bridge_s0_agent:cp_valid
	wire  [149:0] agent_pipeline_source0_data;                                                      // agent_pipeline:out_data -> bar4_emif_cc_bridge_s0_agent:cp_data
	wire          agent_pipeline_source0_ready;                                                     // bar4_emif_cc_bridge_s0_agent:cp_ready -> agent_pipeline:out_ready
	wire    [0:0] agent_pipeline_source0_channel;                                                   // agent_pipeline:out_channel -> bar4_emif_cc_bridge_s0_agent:cp_channel
	wire          agent_pipeline_source0_startofpacket;                                             // agent_pipeline:out_startofpacket -> bar4_emif_cc_bridge_s0_agent:cp_startofpacket
	wire          agent_pipeline_source0_endofpacket;                                               // agent_pipeline:out_endofpacket -> bar4_emif_cc_bridge_s0_agent:cp_endofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rp_valid;                                            // bar4_emif_cc_bridge_s0_agent:rp_valid -> agent_pipeline_001:in_valid
	wire  [149:0] bar4_emif_cc_bridge_s0_agent_rp_data;                                             // bar4_emif_cc_bridge_s0_agent:rp_data -> agent_pipeline_001:in_data
	wire          bar4_emif_cc_bridge_s0_agent_rp_ready;                                            // agent_pipeline_001:in_ready -> bar4_emif_cc_bridge_s0_agent:rp_ready
	wire          bar4_emif_cc_bridge_s0_agent_rp_startofpacket;                                    // bar4_emif_cc_bridge_s0_agent:rp_startofpacket -> agent_pipeline_001:in_startofpacket
	wire          bar4_emif_cc_bridge_s0_agent_rp_endofpacket;                                      // bar4_emif_cc_bridge_s0_agent:rp_endofpacket -> agent_pipeline_001:in_endofpacket
	wire          agent_pipeline_001_source0_valid;                                                 // agent_pipeline_001:out_valid -> router_001:sink_valid
	wire  [149:0] agent_pipeline_001_source0_data;                                                  // agent_pipeline_001:out_data -> router_001:sink_data
	wire          agent_pipeline_001_source0_ready;                                                 // router_001:sink_ready -> agent_pipeline_001:out_ready
	wire          agent_pipeline_001_source0_startofpacket;                                         // agent_pipeline_001:out_startofpacket -> router_001:sink_startofpacket
	wire          agent_pipeline_001_source0_endofpacket;                                           // agent_pipeline_001:out_endofpacket -> router_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                             // cmd_demux:src0_valid -> mux_pipeline:in_valid
	wire  [149:0] cmd_demux_src0_data;                                                              // cmd_demux:src0_data -> mux_pipeline:in_data
	wire          cmd_demux_src0_ready;                                                             // mux_pipeline:in_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                           // cmd_demux:src0_channel -> mux_pipeline:in_channel
	wire          cmd_demux_src0_startofpacket;                                                     // cmd_demux:src0_startofpacket -> mux_pipeline:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                       // cmd_demux:src0_endofpacket -> mux_pipeline:in_endofpacket
	wire          mux_pipeline_source0_valid;                                                       // mux_pipeline:out_valid -> cmd_mux:sink0_valid
	wire  [149:0] mux_pipeline_source0_data;                                                        // mux_pipeline:out_data -> cmd_mux:sink0_data
	wire          mux_pipeline_source0_ready;                                                       // cmd_mux:sink0_ready -> mux_pipeline:out_ready
	wire    [0:0] mux_pipeline_source0_channel;                                                     // mux_pipeline:out_channel -> cmd_mux:sink0_channel
	wire          mux_pipeline_source0_startofpacket;                                               // mux_pipeline:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          mux_pipeline_source0_endofpacket;                                                 // mux_pipeline:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                             // rsp_demux:src0_valid -> mux_pipeline_001:in_valid
	wire  [149:0] rsp_demux_src0_data;                                                              // rsp_demux:src0_data -> mux_pipeline_001:in_data
	wire          rsp_demux_src0_ready;                                                             // mux_pipeline_001:in_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                           // rsp_demux:src0_channel -> mux_pipeline_001:in_channel
	wire          rsp_demux_src0_startofpacket;                                                     // rsp_demux:src0_startofpacket -> mux_pipeline_001:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                       // rsp_demux:src0_endofpacket -> mux_pipeline_001:in_endofpacket
	wire          mux_pipeline_001_source0_valid;                                                   // mux_pipeline_001:out_valid -> rsp_mux:sink0_valid
	wire  [149:0] mux_pipeline_001_source0_data;                                                    // mux_pipeline_001:out_data -> rsp_mux:sink0_data
	wire          mux_pipeline_001_source0_ready;                                                   // rsp_mux:sink0_ready -> mux_pipeline_001:out_ready
	wire    [0:0] mux_pipeline_001_source0_channel;                                                 // mux_pipeline_001:out_channel -> rsp_mux:sink0_channel
	wire          mux_pipeline_001_source0_startofpacket;                                           // mux_pipeline_001:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          mux_pipeline_001_source0_endofpacket;                                             // mux_pipeline_001:out_endofpacket -> rsp_mux:sink0_endofpacket

	bsp_top_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (31),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (4),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (31),
		.UAV_BURSTCOUNT_W            (7),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) bar4_emif_ase_expanded_master_translator (
		.clk                    (a10_pcie_coreclkout_hip_clk),                                                      //   input,   width = 1,                       clk.clk
		.reset                  (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                     reset.reset
		.uav_address            (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_address),       //  output,  width = 31, avalon_universal_master_0.address
		.uav_burstcount         (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 7,                          .burstcount
		.uav_read               (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 8,                          .byteenable
		.uav_readdata           (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 64,                          .readdata
		.uav_writedata          (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 64,                          .writedata
		.uav_lock               (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (bar4_emif_ase_expanded_master_address),                                            //   input,  width = 31,      avalon_anti_master_0.address
		.av_waitrequest         (bar4_emif_ase_expanded_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_burstcount          (bar4_emif_ase_expanded_master_burstcount),                                         //   input,   width = 4,                          .burstcount
		.av_byteenable          (bar4_emif_ase_expanded_master_byteenable),                                         //   input,   width = 8,                          .byteenable
		.av_read                (bar4_emif_ase_expanded_master_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (bar4_emif_ase_expanded_master_readdata),                                           //  output,  width = 64,                          .readdata
		.av_readdatavalid       (bar4_emif_ase_expanded_master_readdatavalid),                                      //  output,   width = 1,                          .readdatavalid
		.av_write               (bar4_emif_ase_expanded_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (bar4_emif_ase_expanded_master_writedata),                                          //   input,  width = 64,                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                             // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                             // (terminated),                                        
		.av_chipselect          (1'b0),                                                                             // (terminated),                                        
		.av_lock                (1'b0),                                                                             // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                             // (terminated),                                        
		.uav_clken              (),                                                                                 // (terminated),                                        
		.av_clken               (1'b1),                                                                             // (terminated),                                        
		.uav_response           (2'b00),                                                                            // (terminated),                                        
		.av_response            (),                                                                                 // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                             // (terminated),                                        
		.av_writeresponsevalid  ()                                                                                  // (terminated),                                        
	);

	bsp_top_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (31),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (3),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (31),
		.UAV_BURSTCOUNT_W               (6),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) bar4_emif_cc_bridge_s0_translator (
		.clk                    (a10_pcie_coreclkout_hip_clk),                                                //   input,   width = 1,                      clk.clk
		.reset                  (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,   width = 1,                    reset.reset
		.uav_address            (bar4_emif_cc_bridge_s0_agent_m0_address),                                    //   input,  width = 31, avalon_universal_slave_0.address
		.uav_burstcount         (bar4_emif_cc_bridge_s0_agent_m0_burstcount),                                 //   input,   width = 6,                         .burstcount
		.uav_read               (bar4_emif_cc_bridge_s0_agent_m0_read),                                       //   input,   width = 1,                         .read
		.uav_write              (bar4_emif_cc_bridge_s0_agent_m0_write),                                      //   input,   width = 1,                         .write
		.uav_waitrequest        (bar4_emif_cc_bridge_s0_agent_m0_waitrequest),                                //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (bar4_emif_cc_bridge_s0_agent_m0_readdatavalid),                              //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (bar4_emif_cc_bridge_s0_agent_m0_byteenable),                                 //   input,   width = 8,                         .byteenable
		.uav_readdata           (bar4_emif_cc_bridge_s0_agent_m0_readdata),                                   //  output,  width = 64,                         .readdata
		.uav_writedata          (bar4_emif_cc_bridge_s0_agent_m0_writedata),                                  //   input,  width = 64,                         .writedata
		.uav_lock               (bar4_emif_cc_bridge_s0_agent_m0_lock),                                       //   input,   width = 1,                         .lock
		.uav_debugaccess        (bar4_emif_cc_bridge_s0_agent_m0_debugaccess),                                //   input,   width = 1,                         .debugaccess
		.av_address             (bar4_emif_cc_bridge_s0_address),                                             //  output,  width = 31,      avalon_anti_slave_0.address
		.av_write               (bar4_emif_cc_bridge_s0_write),                                               //  output,   width = 1,                         .write
		.av_read                (bar4_emif_cc_bridge_s0_read),                                                //  output,   width = 1,                         .read
		.av_readdata            (bar4_emif_cc_bridge_s0_readdata),                                            //   input,  width = 64,                         .readdata
		.av_writedata           (bar4_emif_cc_bridge_s0_writedata),                                           //  output,  width = 64,                         .writedata
		.av_burstcount          (bar4_emif_cc_bridge_s0_burstcount),                                          //  output,   width = 3,                         .burstcount
		.av_byteenable          (bar4_emif_cc_bridge_s0_byteenable),                                          //  output,   width = 8,                         .byteenable
		.av_readdatavalid       (bar4_emif_cc_bridge_s0_readdatavalid),                                       //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (bar4_emif_cc_bridge_s0_waitrequest),                                         //   input,   width = 1,                         .waitrequest
		.av_debugaccess         (bar4_emif_cc_bridge_s0_debugaccess),                                         //  output,   width = 1,                         .debugaccess
		.av_begintransfer       (),                                                                           // (terminated),                                       
		.av_beginbursttransfer  (),                                                                           // (terminated),                                       
		.av_writebyteenable     (),                                                                           // (terminated),                                       
		.av_lock                (),                                                                           // (terminated),                                       
		.av_chipselect          (),                                                                           // (terminated),                                       
		.av_clken               (),                                                                           // (terminated),                                       
		.uav_clken              (1'b0),                                                                       // (terminated),                                       
		.av_outputenable        (),                                                                           // (terminated),                                       
		.uav_response           (),                                                                           // (terminated),                                       
		.av_response            (2'b00),                                                                      // (terminated),                                       
		.uav_writeresponsevalid (),                                                                           // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                        // (terminated),                                       
	);

	bsp_top_altera_merlin_master_agent_191_mpbm6tq #(
		.PKT_WUNIQUE               (149),
		.PKT_DOMAIN_H              (148),
		.PKT_DOMAIN_L              (147),
		.PKT_SNOOP_H               (146),
		.PKT_SNOOP_L               (143),
		.PKT_BARRIER_H             (142),
		.PKT_BARRIER_L             (141),
		.PKT_ORI_BURST_SIZE_H      (140),
		.PKT_ORI_BURST_SIZE_L      (138),
		.PKT_RESPONSE_STATUS_H     (137),
		.PKT_RESPONSE_STATUS_L     (136),
		.PKT_QOS_H                 (125),
		.PKT_QOS_L                 (125),
		.PKT_DATA_SIDEBAND_H       (123),
		.PKT_DATA_SIDEBAND_L       (123),
		.PKT_ADDR_SIDEBAND_H       (122),
		.PKT_ADDR_SIDEBAND_L       (122),
		.PKT_BURST_TYPE_H          (121),
		.PKT_BURST_TYPE_L          (120),
		.PKT_CACHE_H               (135),
		.PKT_CACHE_L               (132),
		.PKT_THREAD_ID_H           (128),
		.PKT_THREAD_ID_L           (128),
		.PKT_BURST_SIZE_H          (119),
		.PKT_BURST_SIZE_L          (117),
		.PKT_TRANS_EXCLUSIVE       (108),
		.PKT_TRANS_LOCK            (107),
		.PKT_BEGIN_BURST           (124),
		.PKT_PROTECTION_H          (131),
		.PKT_PROTECTION_L          (129),
		.PKT_BURSTWRAP_H           (116),
		.PKT_BURSTWRAP_L           (116),
		.PKT_BYTE_CNT_H            (115),
		.PKT_BYTE_CNT_L            (109),
		.PKT_ADDR_H                (102),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (103),
		.PKT_TRANS_POSTED          (104),
		.PKT_TRANS_WRITE           (105),
		.PKT_TRANS_READ            (106),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (126),
		.PKT_SRC_ID_L              (126),
		.PKT_DEST_ID_H             (127),
		.PKT_DEST_ID_L             (127),
		.ST_DATA_W                 (150),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (7),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (1)
	) bar4_emif_ase_expanded_master_agent (
		.clk                   (a10_pcie_coreclkout_hip_clk),                                                      //   input,    width = 1,       clk.clk
		.reset                 (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset),       //   input,    width = 1, clk_reset.reset
		.av_address            (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_address),       //   input,   width = 31,        av.address
		.av_write              (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_write),         //   input,    width = 1,          .write
		.av_read               (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_read),          //   input,    width = 1,          .read
		.av_writedata          (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_writedata),     //   input,   width = 64,          .writedata
		.av_readdata           (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdata),      //  output,   width = 64,          .readdata
		.av_waitrequest        (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_waitrequest),   //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_readdatavalid), //  output,    width = 1,          .readdatavalid
		.av_byteenable         (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_byteenable),    //   input,    width = 8,          .byteenable
		.av_burstcount         (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_burstcount),    //   input,    width = 7,          .burstcount
		.av_debugaccess        (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_debugaccess),   //   input,    width = 1,          .debugaccess
		.av_lock               (bar4_emif_ase_expanded_master_translator_avalon_universal_master_0_lock),          //   input,    width = 1,          .lock
		.cp_valid              (bar4_emif_ase_expanded_master_agent_cp_valid),                                     //  output,    width = 1,        cp.valid
		.cp_data               (bar4_emif_ase_expanded_master_agent_cp_data),                                      //  output,  width = 150,          .data
		.cp_startofpacket      (bar4_emif_ase_expanded_master_agent_cp_startofpacket),                             //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (bar4_emif_ase_expanded_master_agent_cp_endofpacket),                               //  output,    width = 1,          .endofpacket
		.cp_ready              (bar4_emif_ase_expanded_master_agent_cp_ready),                                     //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                 //   input,  width = 150,          .data
		.rp_channel            (rsp_mux_src_channel),                                                              //   input,    width = 1,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                        //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                          //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                                //  output,    width = 1,          .ready
		.av_response           (),                                                                                 // (terminated),                         
		.av_writeresponsevalid ()                                                                                  // (terminated),                         
	);

	bsp_top_altera_merlin_slave_agent_191_ncfkfri #(
		.PKT_ORI_BURST_SIZE_H      (140),
		.PKT_ORI_BURST_SIZE_L      (138),
		.PKT_RESPONSE_STATUS_H     (137),
		.PKT_RESPONSE_STATUS_L     (136),
		.PKT_BURST_SIZE_H          (119),
		.PKT_BURST_SIZE_L          (117),
		.PKT_TRANS_LOCK            (107),
		.PKT_BEGIN_BURST           (124),
		.PKT_PROTECTION_H          (131),
		.PKT_PROTECTION_L          (129),
		.PKT_BURSTWRAP_H           (116),
		.PKT_BURSTWRAP_L           (116),
		.PKT_BYTE_CNT_H            (115),
		.PKT_BYTE_CNT_L            (109),
		.PKT_ADDR_H                (102),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (103),
		.PKT_TRANS_POSTED          (104),
		.PKT_TRANS_WRITE           (105),
		.PKT_TRANS_READ            (106),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (126),
		.PKT_SRC_ID_L              (126),
		.PKT_DEST_ID_H             (127),
		.PKT_DEST_ID_L             (127),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (150),
		.AVS_BURSTCOUNT_W          (6),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (1)
	) bar4_emif_cc_bridge_s0_agent (
		.clk                     (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,             clk.clk
		.reset                   (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1,       clk_reset.reset
		.m0_address              (bar4_emif_cc_bridge_s0_agent_m0_address),                                    //  output,   width = 31,              m0.address
		.m0_burstcount           (bar4_emif_cc_bridge_s0_agent_m0_burstcount),                                 //  output,    width = 6,                .burstcount
		.m0_byteenable           (bar4_emif_cc_bridge_s0_agent_m0_byteenable),                                 //  output,    width = 8,                .byteenable
		.m0_debugaccess          (bar4_emif_cc_bridge_s0_agent_m0_debugaccess),                                //  output,    width = 1,                .debugaccess
		.m0_lock                 (bar4_emif_cc_bridge_s0_agent_m0_lock),                                       //  output,    width = 1,                .lock
		.m0_readdata             (bar4_emif_cc_bridge_s0_agent_m0_readdata),                                   //   input,   width = 64,                .readdata
		.m0_readdatavalid        (bar4_emif_cc_bridge_s0_agent_m0_readdatavalid),                              //   input,    width = 1,                .readdatavalid
		.m0_read                 (bar4_emif_cc_bridge_s0_agent_m0_read),                                       //  output,    width = 1,                .read
		.m0_waitrequest          (bar4_emif_cc_bridge_s0_agent_m0_waitrequest),                                //   input,    width = 1,                .waitrequest
		.m0_writedata            (bar4_emif_cc_bridge_s0_agent_m0_writedata),                                  //  output,   width = 64,                .writedata
		.m0_write                (bar4_emif_cc_bridge_s0_agent_m0_write),                                      //  output,    width = 1,                .write
		.rp_endofpacket          (bar4_emif_cc_bridge_s0_agent_rp_endofpacket),                                //  output,    width = 1,              rp.endofpacket
		.rp_ready                (bar4_emif_cc_bridge_s0_agent_rp_ready),                                      //   input,    width = 1,                .ready
		.rp_valid                (bar4_emif_cc_bridge_s0_agent_rp_valid),                                      //  output,    width = 1,                .valid
		.rp_data                 (bar4_emif_cc_bridge_s0_agent_rp_data),                                       //  output,  width = 150,                .data
		.rp_startofpacket        (bar4_emif_cc_bridge_s0_agent_rp_startofpacket),                              //  output,    width = 1,                .startofpacket
		.cp_ready                (agent_pipeline_source0_ready),                                               //  output,    width = 1,              cp.ready
		.cp_valid                (agent_pipeline_source0_valid),                                               //   input,    width = 1,                .valid
		.cp_data                 (agent_pipeline_source0_data),                                                //   input,  width = 150,                .data
		.cp_startofpacket        (agent_pipeline_source0_startofpacket),                                       //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (agent_pipeline_source0_endofpacket),                                         //   input,    width = 1,                .endofpacket
		.cp_channel              (agent_pipeline_source0_channel),                                             //   input,    width = 1,                .channel
		.rf_sink_ready           (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_ready),                            //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_valid),                            //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_startofpacket),                    //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_endofpacket),                      //   input,    width = 1,                .endofpacket
		.rf_sink_data            (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_data),                             //   input,  width = 151,                .data
		.rf_source_ready         (bar4_emif_cc_bridge_s0_agent_rf_source_ready),                               //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (bar4_emif_cc_bridge_s0_agent_rf_source_valid),                               //  output,    width = 1,                .valid
		.rf_source_startofpacket (bar4_emif_cc_bridge_s0_agent_rf_source_startofpacket),                       //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (bar4_emif_cc_bridge_s0_agent_rf_source_endofpacket),                         //  output,    width = 1,                .endofpacket
		.rf_source_data          (bar4_emif_cc_bridge_s0_agent_rf_source_data),                                //  output,  width = 151,                .data
		.rdata_fifo_sink_ready   (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_ready),                          //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_valid),                          //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_data),                           //   input,   width = 66,                .data
		.rdata_fifo_src_ready    (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_ready),                          //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_valid),                          //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (bar4_emif_cc_bridge_s0_agent_rdata_fifo_src_data),                           //  output,   width = 66,                .data
		.m0_response             (2'b00),                                                                      // (terminated),                               
		.m0_writeresponsevalid   (1'b0),                                                                       // (terminated),                               
		.rdata_fifo_sink_error   (1'b0)                                                                        // (terminated),                               
	);

	bsp_top_altera_avalon_sc_fifo_1930_k6mjsxi #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (151),
		.FIFO_DEPTH          (11),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.SYNC_RESET          (1)
	) bar4_emif_cc_bridge_s0_agent_rsp_fifo (
		.clk               (a10_pcie_coreclkout_hip_clk),                             //   input,    width = 1,       clk.clk
		.reset             (bar4_emif_ase_reset_reset_bridge_in_reset_reset),         //   input,    width = 1, clk_reset.reset
		.in_data           (bar4_emif_cc_bridge_s0_agent_rf_source_data),             //   input,  width = 151,        in.data
		.in_valid          (bar4_emif_cc_bridge_s0_agent_rf_source_valid),            //   input,    width = 1,          .valid
		.in_ready          (bar4_emif_cc_bridge_s0_agent_rf_source_ready),            //  output,    width = 1,          .ready
		.in_startofpacket  (bar4_emif_cc_bridge_s0_agent_rf_source_startofpacket),    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (bar4_emif_cc_bridge_s0_agent_rf_source_endofpacket),      //   input,    width = 1,          .endofpacket
		.out_data          (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_data),          //  output,  width = 151,       out.data
		.out_valid         (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_valid),         //  output,    width = 1,          .valid
		.out_ready         (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_ready),         //   input,    width = 1,          .ready
		.out_startofpacket (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_startofpacket), //  output,    width = 1,          .startofpacket
		.out_endofpacket   (bar4_emif_cc_bridge_s0_agent_rsp_fifo_out_endofpacket),   //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                                   // (terminated),                         
		.csr_read          (1'b0),                                                    // (terminated),                         
		.csr_write         (1'b0),                                                    // (terminated),                         
		.csr_readdata      (),                                                        // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),                    // (terminated),                         
		.almost_full_data  (),                                                        // (terminated),                         
		.almost_empty_data (),                                                        // (terminated),                         
		.in_empty          (1'b0),                                                    // (terminated),                         
		.out_empty         (),                                                        // (terminated),                         
		.in_error          (1'b0),                                                    // (terminated),                         
		.out_error         (),                                                        // (terminated),                         
		.in_channel        (1'b0),                                                    // (terminated),                         
		.out_channel       ()                                                         // (terminated),                         
	);

	bsp_top_altera_merlin_router_1920_zmnka2a router (
		.sink_ready         (bar4_emif_ase_expanded_master_agent_cp_ready),                               //  output,    width = 1,      sink.ready
		.sink_valid         (bar4_emif_ase_expanded_master_agent_cp_valid),                               //   input,    width = 1,          .valid
		.sink_data          (bar4_emif_ase_expanded_master_agent_cp_data),                                //   input,  width = 150,          .data
		.sink_startofpacket (bar4_emif_ase_expanded_master_agent_cp_startofpacket),                       //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (bar4_emif_ase_expanded_master_agent_cp_endofpacket),                         //   input,    width = 1,          .endofpacket
		.clk                (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset              (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                                                           //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                                                           //  output,    width = 1,          .valid
		.src_data           (router_src_data),                                                            //  output,  width = 150,          .data
		.src_channel        (router_src_channel),                                                         //  output,    width = 1,          .channel
		.src_startofpacket  (router_src_startofpacket),                                                   //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                      //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_router_1920_hh6qzfy router_001 (
		.sink_ready         (agent_pipeline_001_source0_ready),                                           //  output,    width = 1,      sink.ready
		.sink_valid         (agent_pipeline_001_source0_valid),                                           //   input,    width = 1,          .valid
		.sink_data          (agent_pipeline_001_source0_data),                                            //   input,  width = 150,          .data
		.sink_startofpacket (agent_pipeline_001_source0_startofpacket),                                   //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (agent_pipeline_001_source0_endofpacket),                                     //   input,    width = 1,          .endofpacket
		.clk                (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset              (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                                                       //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                                                       //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                                                        //  output,  width = 150,          .data
		.src_channel        (router_001_src_channel),                                                     //  output,    width = 1,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                               //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                                  //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_burst_adapter_1920_dkqe6wy #(
		.PKT_ADDR_H                (102),
		.PKT_ADDR_L                (72),
		.PKT_BEGIN_BURST           (124),
		.PKT_BYTE_CNT_H            (115),
		.PKT_BYTE_CNT_L            (109),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_BURST_SIZE_H          (119),
		.PKT_BURST_SIZE_L          (117),
		.PKT_BURST_TYPE_H          (121),
		.PKT_BURST_TYPE_L          (120),
		.PKT_BURSTWRAP_H           (116),
		.PKT_BURSTWRAP_L           (116),
		.PKT_TRANS_COMPRESSED_READ (103),
		.PKT_TRANS_WRITE           (105),
		.PKT_TRANS_READ            (106),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (150),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (114),
		.OUT_BURSTWRAP_H           (116),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("new"),
		.SYNC_RESET                (1)
	) bar4_emif_cc_bridge_s0_burst_adapter (
		.clk                   (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       cr0.clk
		.reset                 (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                                          //   input,    width = 1,     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                                           //   input,  width = 150,          .data
		.sink0_channel         (cmd_mux_src_channel),                                                        //   input,    width = 1,          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                                                  //   input,    width = 1,          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                                    //   input,    width = 1,          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                                          //  output,    width = 1,          .ready
		.source0_valid         (bar4_emif_cc_bridge_s0_burst_adapter_source0_valid),                         //  output,    width = 1,   source0.valid
		.source0_data          (bar4_emif_cc_bridge_s0_burst_adapter_source0_data),                          //  output,  width = 150,          .data
		.source0_channel       (bar4_emif_cc_bridge_s0_burst_adapter_source0_channel),                       //  output,    width = 1,          .channel
		.source0_startofpacket (bar4_emif_cc_bridge_s0_burst_adapter_source0_startofpacket),                 //  output,    width = 1,          .startofpacket
		.source0_endofpacket   (bar4_emif_cc_bridge_s0_burst_adapter_source0_endofpacket),                   //  output,    width = 1,          .endofpacket
		.source0_ready         (bar4_emif_cc_bridge_s0_burst_adapter_source0_ready)                          //   input,    width = 1,          .ready
	);

	bsp_top_altera_merlin_demultiplexer_1921_5pezsdy cmd_demux (
		.clk                (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset              (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                                                           //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                                                         //   input,    width = 1,          .channel
		.sink_data          (router_src_data),                                                            //   input,  width = 150,          .data
		.sink_startofpacket (router_src_startofpacket),                                                   //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                     //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                                                           //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                       //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                       //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                                                        //  output,  width = 150,          .data
		.src0_channel       (cmd_demux_src0_channel),                                                     //  output,    width = 1,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                               //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                                  //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_multiplexer_1921_a6f7tqa cmd_mux (
		.clk                 (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset               (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                          //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                                                          //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                                                           //  output,  width = 150,          .data
		.src_channel         (cmd_mux_src_channel),                                                        //  output,    width = 1,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                                  //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                                    //  output,    width = 1,          .endofpacket
		.sink0_ready         (mux_pipeline_source0_ready),                                                 //  output,    width = 1,     sink0.ready
		.sink0_valid         (mux_pipeline_source0_valid),                                                 //   input,    width = 1,          .valid
		.sink0_channel       (mux_pipeline_source0_channel),                                               //   input,    width = 1,          .channel
		.sink0_data          (mux_pipeline_source0_data),                                                  //   input,  width = 150,          .data
		.sink0_startofpacket (mux_pipeline_source0_startofpacket),                                         //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (mux_pipeline_source0_endofpacket)                                            //   input,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_demultiplexer_1921_5pezsdy rsp_demux (
		.clk                (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset              (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                                                       //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                                                     //   input,    width = 1,          .channel
		.sink_data          (router_001_src_data),                                                        //   input,  width = 150,          .data
		.sink_startofpacket (router_001_src_startofpacket),                                               //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                                 //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                                                       //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                       //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                       //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                                                        //  output,  width = 150,          .data
		.src0_channel       (rsp_demux_src0_channel),                                                     //  output,    width = 1,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                               //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                                  //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_multiplexer_1921_dlyxxha rsp_mux (
		.clk                 (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset               (bar4_emif_ase_expanded_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                          //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                                                          //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                                                           //  output,  width = 150,          .data
		.src_channel         (rsp_mux_src_channel),                                                        //  output,    width = 1,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                                  //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                    //  output,    width = 1,          .endofpacket
		.sink0_ready         (mux_pipeline_001_source0_ready),                                             //  output,    width = 1,     sink0.ready
		.sink0_valid         (mux_pipeline_001_source0_valid),                                             //   input,    width = 1,          .valid
		.sink0_channel       (mux_pipeline_001_source0_channel),                                           //   input,    width = 1,          .channel
		.sink0_data          (mux_pipeline_001_source0_data),                                              //   input,  width = 150,          .data
		.sink0_startofpacket (mux_pipeline_001_source0_startofpacket),                                     //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (mux_pipeline_001_source0_endofpacket)                                        //   input,    width = 1,          .endofpacket
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (150),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) agent_pipeline (
		.clk               (a10_pcie_coreclkout_hip_clk),                                //   input,    width = 1,       cr0.clk
		.reset             (bar4_emif_ase_reset_reset_bridge_in_reset_reset),            //   input,    width = 1, cr0_reset.reset
		.in_ready          (bar4_emif_cc_bridge_s0_burst_adapter_source0_ready),         //  output,    width = 1,     sink0.ready
		.in_valid          (bar4_emif_cc_bridge_s0_burst_adapter_source0_valid),         //   input,    width = 1,          .valid
		.in_startofpacket  (bar4_emif_cc_bridge_s0_burst_adapter_source0_startofpacket), //   input,    width = 1,          .startofpacket
		.in_endofpacket    (bar4_emif_cc_bridge_s0_burst_adapter_source0_endofpacket),   //   input,    width = 1,          .endofpacket
		.in_data           (bar4_emif_cc_bridge_s0_burst_adapter_source0_data),          //   input,  width = 150,          .data
		.in_channel        (bar4_emif_cc_bridge_s0_burst_adapter_source0_channel),       //   input,    width = 1,          .channel
		.out_ready         (agent_pipeline_source0_ready),                               //   input,    width = 1,   source0.ready
		.out_valid         (agent_pipeline_source0_valid),                               //  output,    width = 1,          .valid
		.out_startofpacket (agent_pipeline_source0_startofpacket),                       //  output,    width = 1,          .startofpacket
		.out_endofpacket   (agent_pipeline_source0_endofpacket),                         //  output,    width = 1,          .endofpacket
		.out_data          (agent_pipeline_source0_data),                                //  output,  width = 150,          .data
		.out_channel       (agent_pipeline_source0_channel),                             //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                                       // (terminated),                         
		.out_empty         (),                                                           // (terminated),                         
		.out_error         (),                                                           // (terminated),                         
		.in_error          (1'b0)                                                        // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (150),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (0),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) agent_pipeline_001 (
		.clk               (a10_pcie_coreclkout_hip_clk),                     //   input,    width = 1,       cr0.clk
		.reset             (bar4_emif_ase_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (bar4_emif_cc_bridge_s0_agent_rp_ready),           //  output,    width = 1,     sink0.ready
		.in_valid          (bar4_emif_cc_bridge_s0_agent_rp_valid),           //   input,    width = 1,          .valid
		.in_startofpacket  (bar4_emif_cc_bridge_s0_agent_rp_startofpacket),   //   input,    width = 1,          .startofpacket
		.in_endofpacket    (bar4_emif_cc_bridge_s0_agent_rp_endofpacket),     //   input,    width = 1,          .endofpacket
		.in_data           (bar4_emif_cc_bridge_s0_agent_rp_data),            //   input,  width = 150,          .data
		.out_ready         (agent_pipeline_001_source0_ready),                //   input,    width = 1,   source0.ready
		.out_valid         (agent_pipeline_001_source0_valid),                //  output,    width = 1,          .valid
		.out_startofpacket (agent_pipeline_001_source0_startofpacket),        //  output,    width = 1,          .startofpacket
		.out_endofpacket   (agent_pipeline_001_source0_endofpacket),          //  output,    width = 1,          .endofpacket
		.out_data          (agent_pipeline_001_source0_data),                 //  output,  width = 150,          .data
		.in_empty          (1'b0),                                            // (terminated),                         
		.out_empty         (),                                                // (terminated),                         
		.out_error         (),                                                // (terminated),                         
		.in_error          (1'b0),                                            // (terminated),                         
		.out_channel       (),                                                // (terminated),                         
		.in_channel        (1'b0)                                             // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (150),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) mux_pipeline (
		.clk               (a10_pcie_coreclkout_hip_clk),                     //   input,    width = 1,       cr0.clk
		.reset             (bar4_emif_ase_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (cmd_demux_src0_ready),                            //  output,    width = 1,     sink0.ready
		.in_valid          (cmd_demux_src0_valid),                            //   input,    width = 1,          .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                      //   input,    width = 1,          .endofpacket
		.in_data           (cmd_demux_src0_data),                             //   input,  width = 150,          .data
		.in_channel        (cmd_demux_src0_channel),                          //   input,    width = 1,          .channel
		.out_ready         (mux_pipeline_source0_ready),                      //   input,    width = 1,   source0.ready
		.out_valid         (mux_pipeline_source0_valid),                      //  output,    width = 1,          .valid
		.out_startofpacket (mux_pipeline_source0_startofpacket),              //  output,    width = 1,          .startofpacket
		.out_endofpacket   (mux_pipeline_source0_endofpacket),                //  output,    width = 1,          .endofpacket
		.out_data          (mux_pipeline_source0_data),                       //  output,  width = 150,          .data
		.out_channel       (mux_pipeline_source0_channel),                    //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                            // (terminated),                         
		.out_empty         (),                                                // (terminated),                         
		.out_error         (),                                                // (terminated),                         
		.in_error          (1'b0)                                             // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (150),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) mux_pipeline_001 (
		.clk               (a10_pcie_coreclkout_hip_clk),                     //   input,    width = 1,       cr0.clk
		.reset             (bar4_emif_ase_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (rsp_demux_src0_ready),                            //  output,    width = 1,     sink0.ready
		.in_valid          (rsp_demux_src0_valid),                            //   input,    width = 1,          .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                      //   input,    width = 1,          .endofpacket
		.in_data           (rsp_demux_src0_data),                             //   input,  width = 150,          .data
		.in_channel        (rsp_demux_src0_channel),                          //   input,    width = 1,          .channel
		.out_ready         (mux_pipeline_001_source0_ready),                  //   input,    width = 1,   source0.ready
		.out_valid         (mux_pipeline_001_source0_valid),                  //  output,    width = 1,          .valid
		.out_startofpacket (mux_pipeline_001_source0_startofpacket),          //  output,    width = 1,          .startofpacket
		.out_endofpacket   (mux_pipeline_001_source0_endofpacket),            //  output,    width = 1,          .endofpacket
		.out_data          (mux_pipeline_001_source0_data),                   //  output,  width = 150,          .data
		.out_channel       (mux_pipeline_001_source0_channel),                //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                            // (terminated),                         
		.out_empty         (),                                                // (terminated),                         
		.out_error         (),                                                // (terminated),                         
		.in_error          (1'b0)                                             // (terminated),                         
	);

endmodule
