// bsp_top_altera_mm_interconnect_1920_5uf23dq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module bsp_top_altera_mm_interconnect_1920_5uf23dq (
		input  wire [15:0] bar4_freeze_bridge_slv_bridge_to_pr_address,                                      //                                        bar4_freeze_bridge_slv_bridge_to_pr.address
		output wire        bar4_freeze_bridge_slv_bridge_to_pr_waitrequest,                                  //                                                                           .waitrequest
		input  wire [2:0]  bar4_freeze_bridge_slv_bridge_to_pr_burstcount,                                   //                                                                           .burstcount
		input  wire [7:0]  bar4_freeze_bridge_slv_bridge_to_pr_byteenable,                                   //                                                                           .byteenable
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_beginbursttransfer,                           //                                                                           .beginbursttransfer
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_read,                                         //                                                                           .read
		output wire [63:0] bar4_freeze_bridge_slv_bridge_to_pr_readdata,                                     //                                                                           .readdata
		output wire        bar4_freeze_bridge_slv_bridge_to_pr_readdatavalid,                                //                                                                           .readdatavalid
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_write,                                        //                                                                           .write
		input  wire [63:0] bar4_freeze_bridge_slv_bridge_to_pr_writedata,                                    //                                                                           .writedata
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_lock,                                         //                                                                           .lock
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_debugaccess,                                  //                                                                           .debugaccess
		output wire [1:0]  bar4_freeze_bridge_slv_bridge_to_pr_response,                                     //                                                                           .response
		output wire        bar4_freeze_bridge_slv_bridge_to_pr_writeresponsevalid,                           //                                                                           .writeresponsevalid
		output wire [15:0] local_qsys_0_avs_ctrl_address,                                                    //                                                      local_qsys_0_avs_ctrl.address
		output wire        local_qsys_0_avs_ctrl_write,                                                      //                                                                           .write
		output wire        local_qsys_0_avs_ctrl_read,                                                       //                                                                           .read
		input  wire [63:0] local_qsys_0_avs_ctrl_readdata,                                                   //                                                                           .readdata
		output wire [63:0] local_qsys_0_avs_ctrl_writedata,                                                  //                                                                           .writedata
		output wire [0:0]  local_qsys_0_avs_ctrl_burstcount,                                                 //                                                                           .burstcount
		output wire [7:0]  local_qsys_0_avs_ctrl_byteenable,                                                 //                                                                           .byteenable
		input  wire        local_qsys_0_avs_ctrl_readdatavalid,                                              //                                                                           .readdatavalid
		input  wire        local_qsys_0_avs_ctrl_waitrequest,                                                //                                                                           .waitrequest
		output wire        local_qsys_0_avs_ctrl_debugaccess,                                                //                                                                           .debugaccess
		input  wire        bar4_freeze_bridge_reset_n_reset_bridge_in_reset_reset,                           //                           bar4_freeze_bridge_reset_n_reset_bridge_in_reset.reset
		input  wire        local_qsys_0_reset_reset_bridge_in_reset_reset,                                   //                                   local_qsys_0_reset_reset_bridge_in_reset.reset
		input  wire        bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset, // bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset.reset
		input  wire        local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset,       //       local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset.reset
		input  wire        a10_pcie_coreclkout_hip_clk                                                       //                                                    a10_pcie_coreclkout_hip.clk
	);

	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_debugaccess;        // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_debugaccess -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_debugaccess
	wire   [15:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_address;            // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_address -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_address
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_read;               // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_read -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_read
	wire    [7:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_byteenable;         // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_byteenable -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_byteenable
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdatavalid;      // bar4_freeze_bridge_slv_bridge_to_pr_agent:av_readdatavalid -> bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_readdatavalid
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_waitrequest;        // bar4_freeze_bridge_slv_bridge_to_pr_agent:av_waitrequest -> bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_waitrequest
	wire   [63:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdata;           // bar4_freeze_bridge_slv_bridge_to_pr_agent:av_readdata -> bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_readdata
	wire    [1:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_response;           // bar4_freeze_bridge_slv_bridge_to_pr_agent:av_response -> bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_response
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_lock;               // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_lock -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_lock
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_write;              // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_write -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_write
	wire   [63:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writedata;          // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_writedata -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_writedata
	wire          bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writeresponsevalid; // bar4_freeze_bridge_slv_bridge_to_pr_agent:av_writeresponsevalid -> bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_writeresponsevalid
	wire    [5:0] bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_burstcount;         // bar4_freeze_bridge_slv_bridge_to_pr_translator:uav_burstcount -> bar4_freeze_bridge_slv_bridge_to_pr_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                                           // rsp_mux:src_valid -> bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_valid
	wire  [133:0] rsp_mux_src_data;                                                                            // rsp_mux:src_data -> bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_data
	wire          rsp_mux_src_ready;                                                                           // bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                                         // rsp_mux:src_channel -> bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                                   // rsp_mux:src_startofpacket -> bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                                     // rsp_mux:src_endofpacket -> bar4_freeze_bridge_slv_bridge_to_pr_agent:rp_endofpacket
	wire   [63:0] local_qsys_0_avs_ctrl_agent_m0_readdata;                                                     // local_qsys_0_avs_ctrl_translator:uav_readdata -> local_qsys_0_avs_ctrl_agent:m0_readdata
	wire          local_qsys_0_avs_ctrl_agent_m0_waitrequest;                                                  // local_qsys_0_avs_ctrl_translator:uav_waitrequest -> local_qsys_0_avs_ctrl_agent:m0_waitrequest
	wire          local_qsys_0_avs_ctrl_agent_m0_debugaccess;                                                  // local_qsys_0_avs_ctrl_agent:m0_debugaccess -> local_qsys_0_avs_ctrl_translator:uav_debugaccess
	wire   [15:0] local_qsys_0_avs_ctrl_agent_m0_address;                                                      // local_qsys_0_avs_ctrl_agent:m0_address -> local_qsys_0_avs_ctrl_translator:uav_address
	wire    [7:0] local_qsys_0_avs_ctrl_agent_m0_byteenable;                                                   // local_qsys_0_avs_ctrl_agent:m0_byteenable -> local_qsys_0_avs_ctrl_translator:uav_byteenable
	wire          local_qsys_0_avs_ctrl_agent_m0_read;                                                         // local_qsys_0_avs_ctrl_agent:m0_read -> local_qsys_0_avs_ctrl_translator:uav_read
	wire          local_qsys_0_avs_ctrl_agent_m0_readdatavalid;                                                // local_qsys_0_avs_ctrl_translator:uav_readdatavalid -> local_qsys_0_avs_ctrl_agent:m0_readdatavalid
	wire          local_qsys_0_avs_ctrl_agent_m0_lock;                                                         // local_qsys_0_avs_ctrl_agent:m0_lock -> local_qsys_0_avs_ctrl_translator:uav_lock
	wire   [63:0] local_qsys_0_avs_ctrl_agent_m0_writedata;                                                    // local_qsys_0_avs_ctrl_agent:m0_writedata -> local_qsys_0_avs_ctrl_translator:uav_writedata
	wire          local_qsys_0_avs_ctrl_agent_m0_write;                                                        // local_qsys_0_avs_ctrl_agent:m0_write -> local_qsys_0_avs_ctrl_translator:uav_write
	wire    [3:0] local_qsys_0_avs_ctrl_agent_m0_burstcount;                                                   // local_qsys_0_avs_ctrl_agent:m0_burstcount -> local_qsys_0_avs_ctrl_translator:uav_burstcount
	wire          local_qsys_0_avs_ctrl_agent_rf_source_valid;                                                 // local_qsys_0_avs_ctrl_agent:rf_source_valid -> local_qsys_0_avs_ctrl_agent_rsp_fifo:in_valid
	wire  [134:0] local_qsys_0_avs_ctrl_agent_rf_source_data;                                                  // local_qsys_0_avs_ctrl_agent:rf_source_data -> local_qsys_0_avs_ctrl_agent_rsp_fifo:in_data
	wire          local_qsys_0_avs_ctrl_agent_rf_source_ready;                                                 // local_qsys_0_avs_ctrl_agent_rsp_fifo:in_ready -> local_qsys_0_avs_ctrl_agent:rf_source_ready
	wire          local_qsys_0_avs_ctrl_agent_rf_source_startofpacket;                                         // local_qsys_0_avs_ctrl_agent:rf_source_startofpacket -> local_qsys_0_avs_ctrl_agent_rsp_fifo:in_startofpacket
	wire          local_qsys_0_avs_ctrl_agent_rf_source_endofpacket;                                           // local_qsys_0_avs_ctrl_agent:rf_source_endofpacket -> local_qsys_0_avs_ctrl_agent_rsp_fifo:in_endofpacket
	wire          local_qsys_0_avs_ctrl_agent_rsp_fifo_out_valid;                                              // local_qsys_0_avs_ctrl_agent_rsp_fifo:out_valid -> local_qsys_0_avs_ctrl_agent:rf_sink_valid
	wire  [134:0] local_qsys_0_avs_ctrl_agent_rsp_fifo_out_data;                                               // local_qsys_0_avs_ctrl_agent_rsp_fifo:out_data -> local_qsys_0_avs_ctrl_agent:rf_sink_data
	wire          local_qsys_0_avs_ctrl_agent_rsp_fifo_out_ready;                                              // local_qsys_0_avs_ctrl_agent:rf_sink_ready -> local_qsys_0_avs_ctrl_agent_rsp_fifo:out_ready
	wire          local_qsys_0_avs_ctrl_agent_rsp_fifo_out_startofpacket;                                      // local_qsys_0_avs_ctrl_agent_rsp_fifo:out_startofpacket -> local_qsys_0_avs_ctrl_agent:rf_sink_startofpacket
	wire          local_qsys_0_avs_ctrl_agent_rsp_fifo_out_endofpacket;                                        // local_qsys_0_avs_ctrl_agent_rsp_fifo:out_endofpacket -> local_qsys_0_avs_ctrl_agent:rf_sink_endofpacket
	wire          local_qsys_0_avs_ctrl_agent_rdata_fifo_src_valid;                                            // local_qsys_0_avs_ctrl_agent:rdata_fifo_src_valid -> local_qsys_0_avs_ctrl_agent_rdata_fifo:in_valid
	wire   [65:0] local_qsys_0_avs_ctrl_agent_rdata_fifo_src_data;                                             // local_qsys_0_avs_ctrl_agent:rdata_fifo_src_data -> local_qsys_0_avs_ctrl_agent_rdata_fifo:in_data
	wire          local_qsys_0_avs_ctrl_agent_rdata_fifo_src_ready;                                            // local_qsys_0_avs_ctrl_agent_rdata_fifo:in_ready -> local_qsys_0_avs_ctrl_agent:rdata_fifo_src_ready
	wire          local_qsys_0_avs_ctrl_agent_rdata_fifo_out_valid;                                            // local_qsys_0_avs_ctrl_agent_rdata_fifo:out_valid -> local_qsys_0_avs_ctrl_agent:rdata_fifo_sink_valid
	wire   [65:0] local_qsys_0_avs_ctrl_agent_rdata_fifo_out_data;                                             // local_qsys_0_avs_ctrl_agent_rdata_fifo:out_data -> local_qsys_0_avs_ctrl_agent:rdata_fifo_sink_data
	wire          local_qsys_0_avs_ctrl_agent_rdata_fifo_out_ready;                                            // local_qsys_0_avs_ctrl_agent:rdata_fifo_sink_ready -> local_qsys_0_avs_ctrl_agent_rdata_fifo:out_ready
	wire          bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_valid;                                          // bar4_freeze_bridge_slv_bridge_to_pr_agent:cp_valid -> router:sink_valid
	wire  [133:0] bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_data;                                           // bar4_freeze_bridge_slv_bridge_to_pr_agent:cp_data -> router:sink_data
	wire          bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_ready;                                          // router:sink_ready -> bar4_freeze_bridge_slv_bridge_to_pr_agent:cp_ready
	wire          bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_startofpacket;                                  // bar4_freeze_bridge_slv_bridge_to_pr_agent:cp_startofpacket -> router:sink_startofpacket
	wire          bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_endofpacket;                                    // bar4_freeze_bridge_slv_bridge_to_pr_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                                            // router:src_valid -> cmd_demux:sink_valid
	wire  [133:0] router_src_data;                                                                             // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                                            // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                                          // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                                    // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                                      // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          router_001_src_valid;                                                                        // router_001:src_valid -> rsp_demux:sink_valid
	wire  [133:0] router_001_src_data;                                                                         // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                                        // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                                      // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                                // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                                  // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                                                           // cmd_mux:src_valid -> local_qsys_0_avs_ctrl_burst_adapter:sink0_valid
	wire  [133:0] cmd_mux_src_data;                                                                            // cmd_mux:src_data -> local_qsys_0_avs_ctrl_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                                                           // local_qsys_0_avs_ctrl_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                                         // cmd_mux:src_channel -> local_qsys_0_avs_ctrl_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                                                   // cmd_mux:src_startofpacket -> local_qsys_0_avs_ctrl_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                                                     // cmd_mux:src_endofpacket -> local_qsys_0_avs_ctrl_burst_adapter:sink0_endofpacket
	wire          local_qsys_0_avs_ctrl_burst_adapter_source0_valid;                                           // local_qsys_0_avs_ctrl_burst_adapter:source0_valid -> agent_pipeline:in_valid
	wire  [133:0] local_qsys_0_avs_ctrl_burst_adapter_source0_data;                                            // local_qsys_0_avs_ctrl_burst_adapter:source0_data -> agent_pipeline:in_data
	wire          local_qsys_0_avs_ctrl_burst_adapter_source0_ready;                                           // agent_pipeline:in_ready -> local_qsys_0_avs_ctrl_burst_adapter:source0_ready
	wire    [0:0] local_qsys_0_avs_ctrl_burst_adapter_source0_channel;                                         // local_qsys_0_avs_ctrl_burst_adapter:source0_channel -> agent_pipeline:in_channel
	wire          local_qsys_0_avs_ctrl_burst_adapter_source0_startofpacket;                                   // local_qsys_0_avs_ctrl_burst_adapter:source0_startofpacket -> agent_pipeline:in_startofpacket
	wire          local_qsys_0_avs_ctrl_burst_adapter_source0_endofpacket;                                     // local_qsys_0_avs_ctrl_burst_adapter:source0_endofpacket -> agent_pipeline:in_endofpacket
	wire          agent_pipeline_source0_valid;                                                                // agent_pipeline:out_valid -> local_qsys_0_avs_ctrl_agent:cp_valid
	wire  [133:0] agent_pipeline_source0_data;                                                                 // agent_pipeline:out_data -> local_qsys_0_avs_ctrl_agent:cp_data
	wire          agent_pipeline_source0_ready;                                                                // local_qsys_0_avs_ctrl_agent:cp_ready -> agent_pipeline:out_ready
	wire    [0:0] agent_pipeline_source0_channel;                                                              // agent_pipeline:out_channel -> local_qsys_0_avs_ctrl_agent:cp_channel
	wire          agent_pipeline_source0_startofpacket;                                                        // agent_pipeline:out_startofpacket -> local_qsys_0_avs_ctrl_agent:cp_startofpacket
	wire          agent_pipeline_source0_endofpacket;                                                          // agent_pipeline:out_endofpacket -> local_qsys_0_avs_ctrl_agent:cp_endofpacket
	wire          local_qsys_0_avs_ctrl_agent_rp_valid;                                                        // local_qsys_0_avs_ctrl_agent:rp_valid -> agent_pipeline_001:in_valid
	wire  [133:0] local_qsys_0_avs_ctrl_agent_rp_data;                                                         // local_qsys_0_avs_ctrl_agent:rp_data -> agent_pipeline_001:in_data
	wire          local_qsys_0_avs_ctrl_agent_rp_ready;                                                        // agent_pipeline_001:in_ready -> local_qsys_0_avs_ctrl_agent:rp_ready
	wire          local_qsys_0_avs_ctrl_agent_rp_startofpacket;                                                // local_qsys_0_avs_ctrl_agent:rp_startofpacket -> agent_pipeline_001:in_startofpacket
	wire          local_qsys_0_avs_ctrl_agent_rp_endofpacket;                                                  // local_qsys_0_avs_ctrl_agent:rp_endofpacket -> agent_pipeline_001:in_endofpacket
	wire          agent_pipeline_001_source0_valid;                                                            // agent_pipeline_001:out_valid -> router_001:sink_valid
	wire  [133:0] agent_pipeline_001_source0_data;                                                             // agent_pipeline_001:out_data -> router_001:sink_data
	wire          agent_pipeline_001_source0_ready;                                                            // router_001:sink_ready -> agent_pipeline_001:out_ready
	wire          agent_pipeline_001_source0_startofpacket;                                                    // agent_pipeline_001:out_startofpacket -> router_001:sink_startofpacket
	wire          agent_pipeline_001_source0_endofpacket;                                                      // agent_pipeline_001:out_endofpacket -> router_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                                        // cmd_demux:src0_valid -> mux_pipeline:in_valid
	wire  [133:0] cmd_demux_src0_data;                                                                         // cmd_demux:src0_data -> mux_pipeline:in_data
	wire          cmd_demux_src0_ready;                                                                        // mux_pipeline:in_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                                      // cmd_demux:src0_channel -> mux_pipeline:in_channel
	wire          cmd_demux_src0_startofpacket;                                                                // cmd_demux:src0_startofpacket -> mux_pipeline:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                                  // cmd_demux:src0_endofpacket -> mux_pipeline:in_endofpacket
	wire          mux_pipeline_source0_valid;                                                                  // mux_pipeline:out_valid -> cmd_mux:sink0_valid
	wire  [133:0] mux_pipeline_source0_data;                                                                   // mux_pipeline:out_data -> cmd_mux:sink0_data
	wire          mux_pipeline_source0_ready;                                                                  // cmd_mux:sink0_ready -> mux_pipeline:out_ready
	wire    [0:0] mux_pipeline_source0_channel;                                                                // mux_pipeline:out_channel -> cmd_mux:sink0_channel
	wire          mux_pipeline_source0_startofpacket;                                                          // mux_pipeline:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          mux_pipeline_source0_endofpacket;                                                            // mux_pipeline:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                                        // rsp_demux:src0_valid -> mux_pipeline_001:in_valid
	wire  [133:0] rsp_demux_src0_data;                                                                         // rsp_demux:src0_data -> mux_pipeline_001:in_data
	wire          rsp_demux_src0_ready;                                                                        // mux_pipeline_001:in_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                                      // rsp_demux:src0_channel -> mux_pipeline_001:in_channel
	wire          rsp_demux_src0_startofpacket;                                                                // rsp_demux:src0_startofpacket -> mux_pipeline_001:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                                  // rsp_demux:src0_endofpacket -> mux_pipeline_001:in_endofpacket
	wire          mux_pipeline_001_source0_valid;                                                              // mux_pipeline_001:out_valid -> rsp_mux:sink0_valid
	wire  [133:0] mux_pipeline_001_source0_data;                                                               // mux_pipeline_001:out_data -> rsp_mux:sink0_data
	wire          mux_pipeline_001_source0_ready;                                                              // rsp_mux:sink0_ready -> mux_pipeline_001:out_ready
	wire    [0:0] mux_pipeline_001_source0_channel;                                                            // mux_pipeline_001:out_channel -> rsp_mux:sink0_channel
	wire          mux_pipeline_001_source0_startofpacket;                                                      // mux_pipeline_001:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          mux_pipeline_001_source0_endofpacket;                                                        // mux_pipeline_001:out_endofpacket -> rsp_mux:sink0_endofpacket

	bsp_top_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (16),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (3),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (16),
		.UAV_BURSTCOUNT_W            (6),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (1),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (1),
		.USE_WRITERESPONSE           (1),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) bar4_freeze_bridge_slv_bridge_to_pr_translator (
		.clk                    (a10_pcie_coreclkout_hip_clk),                                                                 //   input,   width = 1,                       clk.clk
		.reset                  (bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset),            //   input,   width = 1,                     reset.reset
		.uav_address            (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_address),            //  output,  width = 16, avalon_universal_master_0.address
		.uav_burstcount         (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_burstcount),         //  output,   width = 6,                          .burstcount
		.uav_read               (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_read),               //  output,   width = 1,                          .read
		.uav_write              (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_write),              //  output,   width = 1,                          .write
		.uav_waitrequest        (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_waitrequest),        //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdatavalid),      //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_byteenable),         //  output,   width = 8,                          .byteenable
		.uav_readdata           (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdata),           //   input,  width = 64,                          .readdata
		.uav_writedata          (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writedata),          //  output,  width = 64,                          .writedata
		.uav_lock               (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_lock),               //  output,   width = 1,                          .lock
		.uav_debugaccess        (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_debugaccess),        //  output,   width = 1,                          .debugaccess
		.uav_response           (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_response),           //   input,   width = 2,                          .response
		.uav_writeresponsevalid (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writeresponsevalid), //   input,   width = 1,                          .writeresponsevalid
		.av_address             (bar4_freeze_bridge_slv_bridge_to_pr_address),                                                 //   input,  width = 16,      avalon_anti_master_0.address
		.av_waitrequest         (bar4_freeze_bridge_slv_bridge_to_pr_waitrequest),                                             //  output,   width = 1,                          .waitrequest
		.av_burstcount          (bar4_freeze_bridge_slv_bridge_to_pr_burstcount),                                              //   input,   width = 3,                          .burstcount
		.av_byteenable          (bar4_freeze_bridge_slv_bridge_to_pr_byteenable),                                              //   input,   width = 8,                          .byteenable
		.av_beginbursttransfer  (bar4_freeze_bridge_slv_bridge_to_pr_beginbursttransfer),                                      //   input,   width = 1,                          .beginbursttransfer
		.av_read                (bar4_freeze_bridge_slv_bridge_to_pr_read),                                                    //   input,   width = 1,                          .read
		.av_readdata            (bar4_freeze_bridge_slv_bridge_to_pr_readdata),                                                //  output,  width = 64,                          .readdata
		.av_readdatavalid       (bar4_freeze_bridge_slv_bridge_to_pr_readdatavalid),                                           //  output,   width = 1,                          .readdatavalid
		.av_write               (bar4_freeze_bridge_slv_bridge_to_pr_write),                                                   //   input,   width = 1,                          .write
		.av_writedata           (bar4_freeze_bridge_slv_bridge_to_pr_writedata),                                               //   input,  width = 64,                          .writedata
		.av_lock                (bar4_freeze_bridge_slv_bridge_to_pr_lock),                                                    //   input,   width = 1,                          .lock
		.av_debugaccess         (bar4_freeze_bridge_slv_bridge_to_pr_debugaccess),                                             //   input,   width = 1,                          .debugaccess
		.av_response            (bar4_freeze_bridge_slv_bridge_to_pr_response),                                                //  output,   width = 2,                          .response
		.av_writeresponsevalid  (bar4_freeze_bridge_slv_bridge_to_pr_writeresponsevalid),                                      //  output,   width = 1,                          .writeresponsevalid
		.av_begintransfer       (1'b0),                                                                                        // (terminated),                                        
		.av_chipselect          (1'b0),                                                                                        // (terminated),                                        
		.uav_clken              (),                                                                                            // (terminated),                                        
		.av_clken               (1'b1)                                                                                         // (terminated),                                        
	);

	bsp_top_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (16),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (16),
		.UAV_BURSTCOUNT_W               (4),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) local_qsys_0_avs_ctrl_translator (
		.clk                    (a10_pcie_coreclkout_hip_clk),                    //   input,   width = 1,                      clk.clk
		.reset                  (local_qsys_0_reset_reset_bridge_in_reset_reset), //   input,   width = 1,                    reset.reset
		.uav_address            (local_qsys_0_avs_ctrl_agent_m0_address),         //   input,  width = 16, avalon_universal_slave_0.address
		.uav_burstcount         (local_qsys_0_avs_ctrl_agent_m0_burstcount),      //   input,   width = 4,                         .burstcount
		.uav_read               (local_qsys_0_avs_ctrl_agent_m0_read),            //   input,   width = 1,                         .read
		.uav_write              (local_qsys_0_avs_ctrl_agent_m0_write),           //   input,   width = 1,                         .write
		.uav_waitrequest        (local_qsys_0_avs_ctrl_agent_m0_waitrequest),     //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (local_qsys_0_avs_ctrl_agent_m0_readdatavalid),   //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (local_qsys_0_avs_ctrl_agent_m0_byteenable),      //   input,   width = 8,                         .byteenable
		.uav_readdata           (local_qsys_0_avs_ctrl_agent_m0_readdata),        //  output,  width = 64,                         .readdata
		.uav_writedata          (local_qsys_0_avs_ctrl_agent_m0_writedata),       //   input,  width = 64,                         .writedata
		.uav_lock               (local_qsys_0_avs_ctrl_agent_m0_lock),            //   input,   width = 1,                         .lock
		.uav_debugaccess        (local_qsys_0_avs_ctrl_agent_m0_debugaccess),     //   input,   width = 1,                         .debugaccess
		.av_address             (local_qsys_0_avs_ctrl_address),                  //  output,  width = 16,      avalon_anti_slave_0.address
		.av_write               (local_qsys_0_avs_ctrl_write),                    //  output,   width = 1,                         .write
		.av_read                (local_qsys_0_avs_ctrl_read),                     //  output,   width = 1,                         .read
		.av_readdata            (local_qsys_0_avs_ctrl_readdata),                 //   input,  width = 64,                         .readdata
		.av_writedata           (local_qsys_0_avs_ctrl_writedata),                //  output,  width = 64,                         .writedata
		.av_burstcount          (local_qsys_0_avs_ctrl_burstcount),               //  output,   width = 1,                         .burstcount
		.av_byteenable          (local_qsys_0_avs_ctrl_byteenable),               //  output,   width = 8,                         .byteenable
		.av_readdatavalid       (local_qsys_0_avs_ctrl_readdatavalid),            //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (local_qsys_0_avs_ctrl_waitrequest),              //   input,   width = 1,                         .waitrequest
		.av_debugaccess         (local_qsys_0_avs_ctrl_debugaccess),              //  output,   width = 1,                         .debugaccess
		.av_begintransfer       (),                                               // (terminated),                                       
		.av_beginbursttransfer  (),                                               // (terminated),                                       
		.av_writebyteenable     (),                                               // (terminated),                                       
		.av_lock                (),                                               // (terminated),                                       
		.av_chipselect          (),                                               // (terminated),                                       
		.av_clken               (),                                               // (terminated),                                       
		.uav_clken              (1'b0),                                           // (terminated),                                       
		.av_outputenable        (),                                               // (terminated),                                       
		.uav_response           (),                                               // (terminated),                                       
		.av_response            (2'b00),                                          // (terminated),                                       
		.uav_writeresponsevalid (),                                               // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                            // (terminated),                                       
	);

	bsp_top_altera_merlin_master_agent_191_mpbm6tq #(
		.PKT_WUNIQUE               (133),
		.PKT_DOMAIN_H              (132),
		.PKT_DOMAIN_L              (131),
		.PKT_SNOOP_H               (130),
		.PKT_SNOOP_L               (127),
		.PKT_BARRIER_H             (126),
		.PKT_BARRIER_L             (125),
		.PKT_ORI_BURST_SIZE_H      (124),
		.PKT_ORI_BURST_SIZE_L      (122),
		.PKT_RESPONSE_STATUS_H     (121),
		.PKT_RESPONSE_STATUS_L     (120),
		.PKT_QOS_H                 (109),
		.PKT_QOS_L                 (109),
		.PKT_DATA_SIDEBAND_H       (107),
		.PKT_DATA_SIDEBAND_L       (107),
		.PKT_ADDR_SIDEBAND_H       (106),
		.PKT_ADDR_SIDEBAND_L       (106),
		.PKT_BURST_TYPE_H          (105),
		.PKT_BURST_TYPE_L          (104),
		.PKT_CACHE_H               (119),
		.PKT_CACHE_L               (116),
		.PKT_THREAD_ID_H           (112),
		.PKT_THREAD_ID_L           (112),
		.PKT_BURST_SIZE_H          (103),
		.PKT_BURST_SIZE_L          (101),
		.PKT_TRANS_EXCLUSIVE       (93),
		.PKT_TRANS_LOCK            (92),
		.PKT_BEGIN_BURST           (108),
		.PKT_PROTECTION_H          (115),
		.PKT_PROTECTION_L          (113),
		.PKT_BURSTWRAP_H           (100),
		.PKT_BURSTWRAP_L           (100),
		.PKT_BYTE_CNT_H            (99),
		.PKT_BYTE_CNT_L            (94),
		.PKT_ADDR_H                (87),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (88),
		.PKT_TRANS_POSTED          (89),
		.PKT_TRANS_WRITE           (90),
		.PKT_TRANS_READ            (91),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (110),
		.PKT_SRC_ID_L              (110),
		.PKT_DEST_ID_H             (111),
		.PKT_DEST_ID_L             (111),
		.ST_DATA_W                 (134),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (6),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (1)
	) bar4_freeze_bridge_slv_bridge_to_pr_agent (
		.clk                   (a10_pcie_coreclkout_hip_clk),                                                                 //   input,    width = 1,       clk.clk
		.reset                 (bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset),            //   input,    width = 1, clk_reset.reset
		.av_address            (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_address),            //   input,   width = 16,        av.address
		.av_write              (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_write),              //   input,    width = 1,          .write
		.av_read               (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_read),               //   input,    width = 1,          .read
		.av_writedata          (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writedata),          //   input,   width = 64,          .writedata
		.av_readdata           (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdata),           //  output,   width = 64,          .readdata
		.av_waitrequest        (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_waitrequest),        //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_readdatavalid),      //  output,    width = 1,          .readdatavalid
		.av_byteenable         (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_byteenable),         //   input,    width = 8,          .byteenable
		.av_burstcount         (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_burstcount),         //   input,    width = 6,          .burstcount
		.av_debugaccess        (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_debugaccess),        //   input,    width = 1,          .debugaccess
		.av_lock               (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_lock),               //   input,    width = 1,          .lock
		.av_response           (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_response),           //  output,    width = 2,          .response
		.av_writeresponsevalid (bar4_freeze_bridge_slv_bridge_to_pr_translator_avalon_universal_master_0_writeresponsevalid), //  output,    width = 1,          .writeresponsevalid
		.cp_valid              (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_valid),                                          //  output,    width = 1,        cp.valid
		.cp_data               (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_data),                                           //  output,  width = 134,          .data
		.cp_startofpacket      (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_startofpacket),                                  //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_endofpacket),                                    //  output,    width = 1,          .endofpacket
		.cp_ready              (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_ready),                                          //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                           //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                            //   input,  width = 134,          .data
		.rp_channel            (rsp_mux_src_channel),                                                                         //   input,    width = 1,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                                   //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                                     //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready)                                                                            //  output,    width = 1,          .ready
	);

	bsp_top_altera_merlin_slave_agent_191_ncfkfri #(
		.PKT_ORI_BURST_SIZE_H      (124),
		.PKT_ORI_BURST_SIZE_L      (122),
		.PKT_RESPONSE_STATUS_H     (121),
		.PKT_RESPONSE_STATUS_L     (120),
		.PKT_BURST_SIZE_H          (103),
		.PKT_BURST_SIZE_L          (101),
		.PKT_TRANS_LOCK            (92),
		.PKT_BEGIN_BURST           (108),
		.PKT_PROTECTION_H          (115),
		.PKT_PROTECTION_L          (113),
		.PKT_BURSTWRAP_H           (100),
		.PKT_BURSTWRAP_L           (100),
		.PKT_BYTE_CNT_H            (99),
		.PKT_BYTE_CNT_L            (94),
		.PKT_ADDR_H                (87),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (88),
		.PKT_TRANS_POSTED          (89),
		.PKT_TRANS_WRITE           (90),
		.PKT_TRANS_READ            (91),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (110),
		.PKT_SRC_ID_L              (110),
		.PKT_DEST_ID_H             (111),
		.PKT_DEST_ID_L             (111),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (134),
		.AVS_BURSTCOUNT_W          (4),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (1)
	) local_qsys_0_avs_ctrl_agent (
		.clk                     (a10_pcie_coreclkout_hip_clk),                            //   input,    width = 1,             clk.clk
		.reset                   (local_qsys_0_reset_reset_bridge_in_reset_reset),         //   input,    width = 1,       clk_reset.reset
		.m0_address              (local_qsys_0_avs_ctrl_agent_m0_address),                 //  output,   width = 16,              m0.address
		.m0_burstcount           (local_qsys_0_avs_ctrl_agent_m0_burstcount),              //  output,    width = 4,                .burstcount
		.m0_byteenable           (local_qsys_0_avs_ctrl_agent_m0_byteenable),              //  output,    width = 8,                .byteenable
		.m0_debugaccess          (local_qsys_0_avs_ctrl_agent_m0_debugaccess),             //  output,    width = 1,                .debugaccess
		.m0_lock                 (local_qsys_0_avs_ctrl_agent_m0_lock),                    //  output,    width = 1,                .lock
		.m0_readdata             (local_qsys_0_avs_ctrl_agent_m0_readdata),                //   input,   width = 64,                .readdata
		.m0_readdatavalid        (local_qsys_0_avs_ctrl_agent_m0_readdatavalid),           //   input,    width = 1,                .readdatavalid
		.m0_read                 (local_qsys_0_avs_ctrl_agent_m0_read),                    //  output,    width = 1,                .read
		.m0_waitrequest          (local_qsys_0_avs_ctrl_agent_m0_waitrequest),             //   input,    width = 1,                .waitrequest
		.m0_writedata            (local_qsys_0_avs_ctrl_agent_m0_writedata),               //  output,   width = 64,                .writedata
		.m0_write                (local_qsys_0_avs_ctrl_agent_m0_write),                   //  output,    width = 1,                .write
		.rp_endofpacket          (local_qsys_0_avs_ctrl_agent_rp_endofpacket),             //  output,    width = 1,              rp.endofpacket
		.rp_ready                (local_qsys_0_avs_ctrl_agent_rp_ready),                   //   input,    width = 1,                .ready
		.rp_valid                (local_qsys_0_avs_ctrl_agent_rp_valid),                   //  output,    width = 1,                .valid
		.rp_data                 (local_qsys_0_avs_ctrl_agent_rp_data),                    //  output,  width = 134,                .data
		.rp_startofpacket        (local_qsys_0_avs_ctrl_agent_rp_startofpacket),           //  output,    width = 1,                .startofpacket
		.cp_ready                (agent_pipeline_source0_ready),                           //  output,    width = 1,              cp.ready
		.cp_valid                (agent_pipeline_source0_valid),                           //   input,    width = 1,                .valid
		.cp_data                 (agent_pipeline_source0_data),                            //   input,  width = 134,                .data
		.cp_startofpacket        (agent_pipeline_source0_startofpacket),                   //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (agent_pipeline_source0_endofpacket),                     //   input,    width = 1,                .endofpacket
		.cp_channel              (agent_pipeline_source0_channel),                         //   input,    width = 1,                .channel
		.rf_sink_ready           (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_ready),         //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_valid),         //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_startofpacket), //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_endofpacket),   //   input,    width = 1,                .endofpacket
		.rf_sink_data            (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_data),          //   input,  width = 135,                .data
		.rf_source_ready         (local_qsys_0_avs_ctrl_agent_rf_source_ready),            //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (local_qsys_0_avs_ctrl_agent_rf_source_valid),            //  output,    width = 1,                .valid
		.rf_source_startofpacket (local_qsys_0_avs_ctrl_agent_rf_source_startofpacket),    //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (local_qsys_0_avs_ctrl_agent_rf_source_endofpacket),      //  output,    width = 1,                .endofpacket
		.rf_source_data          (local_qsys_0_avs_ctrl_agent_rf_source_data),             //  output,  width = 135,                .data
		.rdata_fifo_sink_ready   (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_ready),       //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_valid),       //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_data),        //   input,   width = 66,                .data
		.rdata_fifo_src_ready    (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_ready),       //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_valid),       //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_data),        //  output,   width = 66,                .data
		.m0_response             (2'b00),                                                  // (terminated),                               
		.m0_writeresponsevalid   (1'b0),                                                   // (terminated),                               
		.rdata_fifo_sink_error   (1'b0)                                                    // (terminated),                               
	);

	bsp_top_altera_avalon_sc_fifo_1930_k6mjsxi #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (135),
		.FIFO_DEPTH          (5),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.SYNC_RESET          (1)
	) local_qsys_0_avs_ctrl_agent_rsp_fifo (
		.clk               (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       clk.clk
		.reset             (local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.in_data           (local_qsys_0_avs_ctrl_agent_rf_source_data),                                 //   input,  width = 135,        in.data
		.in_valid          (local_qsys_0_avs_ctrl_agent_rf_source_valid),                                //   input,    width = 1,          .valid
		.in_ready          (local_qsys_0_avs_ctrl_agent_rf_source_ready),                                //  output,    width = 1,          .ready
		.in_startofpacket  (local_qsys_0_avs_ctrl_agent_rf_source_startofpacket),                        //   input,    width = 1,          .startofpacket
		.in_endofpacket    (local_qsys_0_avs_ctrl_agent_rf_source_endofpacket),                          //   input,    width = 1,          .endofpacket
		.out_data          (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_data),                              //  output,  width = 135,       out.data
		.out_valid         (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_valid),                             //  output,    width = 1,          .valid
		.out_ready         (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_ready),                             //   input,    width = 1,          .ready
		.out_startofpacket (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_startofpacket),                     //  output,    width = 1,          .startofpacket
		.out_endofpacket   (local_qsys_0_avs_ctrl_agent_rsp_fifo_out_endofpacket),                       //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                                                      // (terminated),                         
		.csr_read          (1'b0),                                                                       // (terminated),                         
		.csr_write         (1'b0),                                                                       // (terminated),                         
		.csr_readdata      (),                                                                           // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),                                       // (terminated),                         
		.almost_full_data  (),                                                                           // (terminated),                         
		.almost_empty_data (),                                                                           // (terminated),                         
		.in_empty          (1'b0),                                                                       // (terminated),                         
		.out_empty         (),                                                                           // (terminated),                         
		.in_error          (1'b0),                                                                       // (terminated),                         
		.out_error         (),                                                                           // (terminated),                         
		.in_channel        (1'b0),                                                                       // (terminated),                         
		.out_channel       ()                                                                            // (terminated),                         
	);

	bsp_top_altera_avalon_sc_fifo_1930_k6mjsxi #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (66),
		.FIFO_DEPTH          (8),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.SYNC_RESET          (1)
	) local_qsys_0_avs_ctrl_agent_rdata_fifo (
		.clk               (a10_pcie_coreclkout_hip_clk),                                                //   input,   width = 1,       clk.clk
		.reset             (local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset), //   input,   width = 1, clk_reset.reset
		.in_data           (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_data),                            //   input,  width = 66,        in.data
		.in_valid          (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_valid),                           //   input,   width = 1,          .valid
		.in_ready          (local_qsys_0_avs_ctrl_agent_rdata_fifo_src_ready),                           //  output,   width = 1,          .ready
		.out_data          (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_data),                            //  output,  width = 66,       out.data
		.out_valid         (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_valid),                           //  output,   width = 1,          .valid
		.out_ready         (local_qsys_0_avs_ctrl_agent_rdata_fifo_out_ready),                           //   input,   width = 1,          .ready
		.csr_address       (2'b00),                                                                      // (terminated),                        
		.csr_read          (1'b0),                                                                       // (terminated),                        
		.csr_write         (1'b0),                                                                       // (terminated),                        
		.csr_readdata      (),                                                                           // (terminated),                        
		.csr_writedata     (32'b00000000000000000000000000000000),                                       // (terminated),                        
		.almost_full_data  (),                                                                           // (terminated),                        
		.almost_empty_data (),                                                                           // (terminated),                        
		.in_startofpacket  (1'b0),                                                                       // (terminated),                        
		.in_endofpacket    (1'b0),                                                                       // (terminated),                        
		.out_startofpacket (),                                                                           // (terminated),                        
		.out_endofpacket   (),                                                                           // (terminated),                        
		.in_empty          (1'b0),                                                                       // (terminated),                        
		.out_empty         (),                                                                           // (terminated),                        
		.in_error          (1'b0),                                                                       // (terminated),                        
		.out_error         (),                                                                           // (terminated),                        
		.in_channel        (1'b0),                                                                       // (terminated),                        
		.out_channel       ()                                                                            // (terminated),                        
	);

	bsp_top_altera_merlin_router_1920_jd4jcfq router (
		.sink_ready         (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_ready),                               //  output,    width = 1,      sink.ready
		.sink_valid         (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_valid),                               //   input,    width = 1,          .valid
		.sink_data          (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_data),                                //   input,  width = 134,          .data
		.sink_startofpacket (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_startofpacket),                       //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (bar4_freeze_bridge_slv_bridge_to_pr_agent_cp_endofpacket),                         //   input,    width = 1,          .endofpacket
		.clk                (a10_pcie_coreclkout_hip_clk),                                                      //   input,    width = 1,       clk.clk
		.reset              (bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                                                                 //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                                                                 //  output,    width = 1,          .valid
		.src_data           (router_src_data),                                                                  //  output,  width = 134,          .data
		.src_channel        (router_src_channel),                                                               //  output,    width = 1,          .channel
		.src_startofpacket  (router_src_startofpacket),                                                         //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                            //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_router_1920_4v44fpq router_001 (
		.sink_ready         (agent_pipeline_001_source0_ready),               //  output,    width = 1,      sink.ready
		.sink_valid         (agent_pipeline_001_source0_valid),               //   input,    width = 1,          .valid
		.sink_data          (agent_pipeline_001_source0_data),                //   input,  width = 134,          .data
		.sink_startofpacket (agent_pipeline_001_source0_startofpacket),       //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (agent_pipeline_001_source0_endofpacket),         //   input,    width = 1,          .endofpacket
		.clk                (a10_pcie_coreclkout_hip_clk),                    //   input,    width = 1,       clk.clk
		.reset              (local_qsys_0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                           //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                           //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                            //  output,  width = 134,          .data
		.src_channel        (router_001_src_channel),                         //  output,    width = 1,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                   //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                      //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_burst_adapter_1920_glomr3i #(
		.PKT_ADDR_H                (87),
		.PKT_ADDR_L                (72),
		.PKT_BEGIN_BURST           (108),
		.PKT_BYTE_CNT_H            (99),
		.PKT_BYTE_CNT_L            (94),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_BURST_SIZE_H          (103),
		.PKT_BURST_SIZE_L          (101),
		.PKT_BURST_TYPE_H          (105),
		.PKT_BURST_TYPE_L          (104),
		.PKT_BURSTWRAP_H           (100),
		.PKT_BURSTWRAP_L           (100),
		.PKT_TRANS_COMPRESSED_READ (88),
		.PKT_TRANS_WRITE           (90),
		.PKT_TRANS_READ            (91),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (134),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (97),
		.OUT_BURSTWRAP_H           (100),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("new"),
		.SYNC_RESET                (1)
	) local_qsys_0_avs_ctrl_burst_adapter (
		.clk                   (a10_pcie_coreclkout_hip_clk),                               //   input,    width = 1,       cr0.clk
		.reset                 (local_qsys_0_reset_reset_bridge_in_reset_reset),            //   input,    width = 1, cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                         //   input,    width = 1,     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                          //   input,  width = 134,          .data
		.sink0_channel         (cmd_mux_src_channel),                                       //   input,    width = 1,          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                                 //   input,    width = 1,          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                   //   input,    width = 1,          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                         //  output,    width = 1,          .ready
		.source0_valid         (local_qsys_0_avs_ctrl_burst_adapter_source0_valid),         //  output,    width = 1,   source0.valid
		.source0_data          (local_qsys_0_avs_ctrl_burst_adapter_source0_data),          //  output,  width = 134,          .data
		.source0_channel       (local_qsys_0_avs_ctrl_burst_adapter_source0_channel),       //  output,    width = 1,          .channel
		.source0_startofpacket (local_qsys_0_avs_ctrl_burst_adapter_source0_startofpacket), //  output,    width = 1,          .startofpacket
		.source0_endofpacket   (local_qsys_0_avs_ctrl_burst_adapter_source0_endofpacket),   //  output,    width = 1,          .endofpacket
		.source0_ready         (local_qsys_0_avs_ctrl_burst_adapter_source0_ready)          //   input,    width = 1,          .ready
	);

	bsp_top_altera_merlin_demultiplexer_1921_lsxip2y cmd_demux (
		.clk                (a10_pcie_coreclkout_hip_clk),                                                      //   input,    width = 1,       clk.clk
		.reset              (bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                                                                 //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                                                               //   input,    width = 1,          .channel
		.sink_data          (router_src_data),                                                                  //   input,  width = 134,          .data
		.sink_startofpacket (router_src_startofpacket),                                                         //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                           //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                                                                 //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                             //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                             //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                                                              //  output,  width = 134,          .data
		.src0_channel       (cmd_demux_src0_channel),                                                           //  output,    width = 1,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                                     //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                                        //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_multiplexer_1921_gzefhta cmd_mux (
		.clk                 (a10_pcie_coreclkout_hip_clk),                    //   input,    width = 1,       clk.clk
		.reset               (local_qsys_0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                              //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                              //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                               //  output,  width = 134,          .data
		.src_channel         (cmd_mux_src_channel),                            //  output,    width = 1,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                      //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                        //  output,    width = 1,          .endofpacket
		.sink0_ready         (mux_pipeline_source0_ready),                     //  output,    width = 1,     sink0.ready
		.sink0_valid         (mux_pipeline_source0_valid),                     //   input,    width = 1,          .valid
		.sink0_channel       (mux_pipeline_source0_channel),                   //   input,    width = 1,          .channel
		.sink0_data          (mux_pipeline_source0_data),                      //   input,  width = 134,          .data
		.sink0_startofpacket (mux_pipeline_source0_startofpacket),             //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (mux_pipeline_source0_endofpacket)                //   input,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_demultiplexer_1921_lsxip2y rsp_demux (
		.clk                (a10_pcie_coreclkout_hip_clk),                    //   input,    width = 1,       clk.clk
		.reset              (local_qsys_0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                           //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                         //   input,    width = 1,          .channel
		.sink_data          (router_001_src_data),                            //   input,  width = 134,          .data
		.sink_startofpacket (router_001_src_startofpacket),                   //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                     //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                           //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                           //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                           //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                            //  output,  width = 134,          .data
		.src0_channel       (rsp_demux_src0_channel),                         //  output,    width = 1,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                   //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                      //  output,    width = 1,          .endofpacket
	);

	bsp_top_altera_merlin_multiplexer_1921_hopjadi rsp_mux (
		.clk                 (a10_pcie_coreclkout_hip_clk),                                                      //   input,    width = 1,       clk.clk
		.reset               (bar4_freeze_bridge_slv_bridge_to_pr_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                                //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                                                                //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                                                                 //  output,  width = 134,          .data
		.src_channel         (rsp_mux_src_channel),                                                              //  output,    width = 1,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                                        //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                          //  output,    width = 1,          .endofpacket
		.sink0_ready         (mux_pipeline_001_source0_ready),                                                   //  output,    width = 1,     sink0.ready
		.sink0_valid         (mux_pipeline_001_source0_valid),                                                   //   input,    width = 1,          .valid
		.sink0_channel       (mux_pipeline_001_source0_channel),                                                 //   input,    width = 1,          .channel
		.sink0_data          (mux_pipeline_001_source0_data),                                                    //   input,  width = 134,          .data
		.sink0_startofpacket (mux_pipeline_001_source0_startofpacket),                                           //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (mux_pipeline_001_source0_endofpacket)                                              //   input,    width = 1,          .endofpacket
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (134),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) agent_pipeline (
		.clk               (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       cr0.clk
		.reset             (local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (local_qsys_0_avs_ctrl_burst_adapter_source0_ready),                          //  output,    width = 1,     sink0.ready
		.in_valid          (local_qsys_0_avs_ctrl_burst_adapter_source0_valid),                          //   input,    width = 1,          .valid
		.in_startofpacket  (local_qsys_0_avs_ctrl_burst_adapter_source0_startofpacket),                  //   input,    width = 1,          .startofpacket
		.in_endofpacket    (local_qsys_0_avs_ctrl_burst_adapter_source0_endofpacket),                    //   input,    width = 1,          .endofpacket
		.in_data           (local_qsys_0_avs_ctrl_burst_adapter_source0_data),                           //   input,  width = 134,          .data
		.in_channel        (local_qsys_0_avs_ctrl_burst_adapter_source0_channel),                        //   input,    width = 1,          .channel
		.out_ready         (agent_pipeline_source0_ready),                                               //   input,    width = 1,   source0.ready
		.out_valid         (agent_pipeline_source0_valid),                                               //  output,    width = 1,          .valid
		.out_startofpacket (agent_pipeline_source0_startofpacket),                                       //  output,    width = 1,          .startofpacket
		.out_endofpacket   (agent_pipeline_source0_endofpacket),                                         //  output,    width = 1,          .endofpacket
		.out_data          (agent_pipeline_source0_data),                                                //  output,  width = 134,          .data
		.out_channel       (agent_pipeline_source0_channel),                                             //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                                                       // (terminated),                         
		.out_empty         (),                                                                           // (terminated),                         
		.out_error         (),                                                                           // (terminated),                         
		.in_error          (1'b0)                                                                        // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (134),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (0),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) agent_pipeline_001 (
		.clk               (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       cr0.clk
		.reset             (local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (local_qsys_0_avs_ctrl_agent_rp_ready),                                       //  output,    width = 1,     sink0.ready
		.in_valid          (local_qsys_0_avs_ctrl_agent_rp_valid),                                       //   input,    width = 1,          .valid
		.in_startofpacket  (local_qsys_0_avs_ctrl_agent_rp_startofpacket),                               //   input,    width = 1,          .startofpacket
		.in_endofpacket    (local_qsys_0_avs_ctrl_agent_rp_endofpacket),                                 //   input,    width = 1,          .endofpacket
		.in_data           (local_qsys_0_avs_ctrl_agent_rp_data),                                        //   input,  width = 134,          .data
		.out_ready         (agent_pipeline_001_source0_ready),                                           //   input,    width = 1,   source0.ready
		.out_valid         (agent_pipeline_001_source0_valid),                                           //  output,    width = 1,          .valid
		.out_startofpacket (agent_pipeline_001_source0_startofpacket),                                   //  output,    width = 1,          .startofpacket
		.out_endofpacket   (agent_pipeline_001_source0_endofpacket),                                     //  output,    width = 1,          .endofpacket
		.out_data          (agent_pipeline_001_source0_data),                                            //  output,  width = 134,          .data
		.in_empty          (1'b0),                                                                       // (terminated),                         
		.out_empty         (),                                                                           // (terminated),                         
		.out_error         (),                                                                           // (terminated),                         
		.in_error          (1'b0),                                                                       // (terminated),                         
		.out_channel       (),                                                                           // (terminated),                         
		.in_channel        (1'b0)                                                                        // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (134),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) mux_pipeline (
		.clk               (a10_pcie_coreclkout_hip_clk),                                                //   input,    width = 1,       cr0.clk
		.reset             (local_qsys_0_avs_ctrl_agent_rsp_fifo_clk_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (cmd_demux_src0_ready),                                                       //  output,    width = 1,     sink0.ready
		.in_valid          (cmd_demux_src0_valid),                                                       //   input,    width = 1,          .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                                               //   input,    width = 1,          .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                                                 //   input,    width = 1,          .endofpacket
		.in_data           (cmd_demux_src0_data),                                                        //   input,  width = 134,          .data
		.in_channel        (cmd_demux_src0_channel),                                                     //   input,    width = 1,          .channel
		.out_ready         (mux_pipeline_source0_ready),                                                 //   input,    width = 1,   source0.ready
		.out_valid         (mux_pipeline_source0_valid),                                                 //  output,    width = 1,          .valid
		.out_startofpacket (mux_pipeline_source0_startofpacket),                                         //  output,    width = 1,          .startofpacket
		.out_endofpacket   (mux_pipeline_source0_endofpacket),                                           //  output,    width = 1,          .endofpacket
		.out_data          (mux_pipeline_source0_data),                                                  //  output,  width = 134,          .data
		.out_channel       (mux_pipeline_source0_channel),                                               //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                                                       // (terminated),                         
		.out_empty         (),                                                                           // (terminated),                         
		.out_error         (),                                                                           // (terminated),                         
		.in_error          (1'b0)                                                                        // (terminated),                         
	);

	bsp_top_altera_avalon_st_pipeline_stage_1920_zterisq #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (134),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (1),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1),
		.SYNC_RESET       (1)
	) mux_pipeline_001 (
		.clk               (a10_pcie_coreclkout_hip_clk),                            //   input,    width = 1,       cr0.clk
		.reset             (bar4_freeze_bridge_reset_n_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.in_ready          (rsp_demux_src0_ready),                                   //  output,    width = 1,     sink0.ready
		.in_valid          (rsp_demux_src0_valid),                                   //   input,    width = 1,          .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                           //   input,    width = 1,          .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                             //   input,    width = 1,          .endofpacket
		.in_data           (rsp_demux_src0_data),                                    //   input,  width = 134,          .data
		.in_channel        (rsp_demux_src0_channel),                                 //   input,    width = 1,          .channel
		.out_ready         (mux_pipeline_001_source0_ready),                         //   input,    width = 1,   source0.ready
		.out_valid         (mux_pipeline_001_source0_valid),                         //  output,    width = 1,          .valid
		.out_startofpacket (mux_pipeline_001_source0_startofpacket),                 //  output,    width = 1,          .startofpacket
		.out_endofpacket   (mux_pipeline_001_source0_endofpacket),                   //  output,    width = 1,          .endofpacket
		.out_data          (mux_pipeline_001_source0_data),                          //  output,  width = 134,          .data
		.out_channel       (mux_pipeline_001_source0_channel),                       //  output,    width = 1,          .channel
		.in_empty          (1'b0),                                                   // (terminated),                         
		.out_empty         (),                                                       // (terminated),                         
		.out_error         (),                                                       // (terminated),                         
		.in_error          (1'b0)                                                    // (terminated),                         
	);

endmodule
